### ISSUE TITLE
WebGL Warning with custom pipeline

### ISSUE THREAD

**Issue by amcolash** [photonstorm/phaser#4485] opened 2019-04-23 06:46 UTC
## Version

* Phaser Version: 3.15.1 & 3.16.2

* Operating system: Linux (Ubuntu, 18.04)

* Browser: Chrome 73

## Description

Using a custom pipeline, there is a webgl warning that shows up: `WebGL: INVALID_VALUE: disableVertexAttribArray: index out of range`. I am using a very simple fragment shader (grayscale) extended off of the `TextureTintPipeline`, but also found it was happening in the phaser example site for custom pipelines. In my code, I am using phaser 3.16.2, in the examples it is 3.15.1.

## Example Test Code

Please see: https://labs.phaser.io/edit.html?src=src\renderer\Custom%20Pipeline.js. Open the chrome dev tools and see the warning messages.

## Additional Information

Here is a stack trace:
```
WebGLPipeline.js:347 WebGL: too many errors, no more errors will be reported to the console for this context.
bind @ WebGLPipeline.js:347
setPipeline @ WebGLRenderer.js:957
batchSprite @ TextureTintPipeline.js:519
SpriteWebGLRenderer @ SpriteWebGLRenderer.js:24
ContainerWebGLRenderer @ ContainerWebGLRenderer.js:83
render @ WebGLRenderer.js:1900
render @ CameraManager.js:606
render @ Systems.js:392
render @ SceneManager.js:584
step @ Game.js:490
step @ TimeStep.js:558
step @ RequestAnimationFrame.js:105
requestAnimationFrame (async)
step @ RequestAnimationFrame.js:107
requestAnimationFrame (async)
```

Area of issue:
```
    if (location >= 0) {
        gl.enableVertexAttribArray(location);
        gl.vertexAttribPointer(location, element.size, element.type, element.normalized, vertexSize, element.offset);
    } else {
-->     gl.disableVertexAttribArray(location);
    }
```

Debugging a bit, it appears that `location = -1` when this issue happens. I am not too familiar with the inner-workings of phaser + webgl, so without more context, I can't help too much more at the moment.

It looks like this issue may be similar to the one found here, but not entirely sure (things are not present in the fragment shader that were expected): https://stackoverflow.com/questions/53664857/webgl-invalid-value-vertexattribpointer-index-out-of-range-invalid-value-en/53669308

Let me know if there is any other info I can provide.

**Comment by photonstorm** [comment] 2019-04-24 13:00
This must be GPU / OS specific, as I get no such errors on Windows 10 or macOS in any version of Phaser from 3.15+ (testing on Chrome Canary 76)

**Comment by jcyuan** [comment] 2019-04-24 13:16
no error found on the example site.
imo usually this API will be used when switch between shaders because you have to 'clear' stuffs of the previous shader.
actually I'm using some customized pipeline and no error found.

**Comment by photonstorm** [comment] 2019-07-15 14:30
Closing this issue off as it's been a few months now, with several releases since, and cannot be reproduced using the provided example on any current version.

**Closed by photonstorm** 2019-07-15 14:30 UTC
Labels: 🦔 Need to reproduce
