### ISSUE TITLE
Uninitialized object in the `phaser.js` build, even though it seems fine in source

### ISSUE THREAD

**Issue by steve-perkins** [photonstorm/phaser#2612] opened 2016-07-10 20:46 UTC
When using the Arcade physics engine, and executing `overlap()` with a sprite and group, I encountered a strange error: `Cannot set property 'x' of undefined`.  The call stack ends at `getBounds @ phaser.js:87782`, being called by `collideSpriteVsGroup @ phaser.js:85221`.  The code around that line looks like this:

            var bounds;

            for (var i = 0; i < group.hash.length; i++)
            {
                var object1 = group.hash[i];

                //  Skip duff entries - we can't check a non-existent sprite or one with no body
                if (!object1 || !object1.exists || !object1.body)
                {
                    continue;
                }

                //  Inject the Body bounds data into the bounds object
                bounds = object1.body.getBounds(bounds);

As you can see, the first line in this snippet declares a `bounds` variable... but *never initializes it*.  The undefined value is the passed to `getBounds` on the last nine, which blows up because it expects the value to be a defined object.

I forked the code to submit a pull request, and discovered something odd.  The problem seems to be already fixed in the `dev` branch (i.e. line 709 of `src/physics/arcade/World.js`).  However, it's still broken in the `dev` branch built version (i.e. line 85208 of `build/phaser.js`).  Could there be an issue with the build process?

**Comment by drhayes** [comment] 2016-07-10 22:48
Dupe of #2610?

**Comment by photonstorm** [comment] 2016-07-11 09:16
This is fixed in the 2.6.1 release which was published just now.

**Closed by photonstorm** 2016-07-11 09:16 UTC
