### ISSUE TITLE
how do I set the max fps for the game? fps.target in GameConfig is  not work

### ISSUE THREAD

**Issue by xdkaka** [photonstorm/phaser#4837] opened 2019-11-01 09:46 UTC
## Version

* Phaser Version: 3.210.1

* Operating system:

* Browser:Chrome

## Description

how do I set the max fps for the game? fps.target in GameConfig is not work

**Comment by samme** [comment] 2019-11-05 00:16
#4229

**Comment by photonstorm** [comment] 2019-11-20 14:01
Duplicate of #4229 - please track in there.

**Closed by photonstorm** 2019-11-20 14:01 UTC
