### ISSUE TITLE
Typings install leads to error

### ISSUE THREAD

**Issue by kidproquo** [photonstorm/phaser#2735] opened 2016-09-02 20:54 UTC
Tried installing the typings:
`typings install github:photonstorm/phaser/typescript/typings.json -GD`

Compiling gives me loads of errors (this is the last few lines):
```
ERROR in [default] /Users/prince/Developer/games/typo/typings/main/definitions/phaser/index.d.ts:33773:150 
Cannot find namespace 'PIXI'.

ERROR in [default] /Users/prince/Developer/games/typo/typings/main/definitions/phaser/index.d.ts:34005:80 
Cannot find namespace 'PIXI'.

ERROR in [default] /Users/prince/Developer/games/typo/typings/main/definitions/phaser/index.d.ts:34229:92 
Cannot find namespace 'PIXI'.

ERROR in [default] /Users/prince/Developer/games/typo/typings/main/definitions/phaser/index.d.ts:34269:98 
Cannot find namespace 'PIXI'.

ERROR in [default] /Users/prince/Developer/games/typo/typings/main/definitions/phaser/index.d.ts:36533:0 
Duplicate identifier 'export='.

ERROR in [default] /Users/prince/Developer/games/typo/typings/main/definitions/phaser/index.d.ts:36537:0 
Duplicate identifier 'export='.
```
Googling around suggests this could be because of duplicate files getting compiled. Tried deleting the type definitions from the node_modules directory `node_modules/phaser/typescript`, but got the same errors.

The only way that I have managed to get it to work is by reverting to the old method of referring to the phaser.d.ts file from the `node_modules/phaser/typescript` directory.

**Comment by photonstorm** [comment] 2016-09-27 19:23
Closing as this is a duplicate of #2746 (please track that for a resolution)

**Closed by photonstorm** 2016-09-27 19:23 UTC
Labels: TypeScript
