### ISSUE TITLE
No sound on ios 9

### ISSUE THREAD

**Issue by MyCatCarlos** [photonstorm/phaser#2095] opened 2015-09-17 11:12 UTC
No sound on ios 9 (safari and chrome). Tested with phaser audio examples (2.4.3) and own game (2.3.0).

**Comment by Cristy94** [comment] 2015-09-17 11:24
What format of audio files do you use? Does it work in iOS 8?

**Comment by MyCatCarlos** [comment] 2015-09-17 11:26
mp3-files, it worked on ios 8.4.1

**Comment by photonstorm** [comment] 2015-09-17 11:50
Any errors in the console when it tries to play them? (You can see this if you hook an iOS device to a Mac and run Safari in debug mode). If it's trying to hit a Web Audio API that no longer exists then we'll need to fix this of course.

**Comment by MyCatCarlos** [comment] 2015-09-17 12:10
No errors in console while remote debugging (tested with audio demo's 'fade in' and 'loop')

**Comment by photonstorm** [comment] 2015-09-17 12:50
Hmm - how about using something other than an mp3? An m4a perhaps (proper Apple native format). Would rule that out at least.

**Comment by photonstorm** [comment] 2015-09-22 10:47
This is now fixed in dev. Sodding Apple.

**Closed by photonstorm** 2015-09-22 10:47 UTC

**Comment by MyCatCarlos** [comment] 2015-09-22 11:43
Thanks !

**Comment by Cristy94** [comment] 2015-09-22 23:22
So I guess this is because of 3D Touch/force touch? Now the touchstart won't trigger events as before? Won't this affect/break other things too in Phaser?

**Comment by photonstorm** [comment] 2015-09-23 08:25
According to the issue in the webkit bug tracker it looks like a regression rather than done on purpose.
