### ISSUE TITLE
Remove Texture and Reload it with same Key do not work

### ISSUE THREAD

**Issue by giviz** [photonstorm/phaser#4720] opened 2019-08-21 23:32 UTC
## Version

* Phaser Version: v3.17.0

* Operating system: Mac OS

* Browser:

## Description

Load an atlas with key1.
Remove that atlas.
Reload that atlas with key1, it's not working.

## Example Test Code

```
var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload() {

    this.load.path = 'assets/atlas/';

    this.load.multiatlas('megaset', 'tp3-multi-atlas.json');
}

function create() {
    this.bunny = this.add.image(300, 130, 'megaset', 'bunny').setOrigin(0); // un-trimmed

    this.bunny.destroy();

    this.textures.remove('megaset');

    // Will not work because texture key is the same
    this.load.multiatlas('megaset', 'tp3-multi-atlas.json');
    this.load.once('complete', () => {
        console.log('load complete');
        this.bunny = this.add.image(300, 130, 'megaset', 'bunny').setOrigin(0);    
    });
    this.load.start();

    // Will work because key is different
    this.load.multiatlas('megaset2', 'tp3-multi-atlas.json');
    this.load.once('complete', () => {
        console.log('load complete2');
        this.bunny = this.add.image(300, 130, 'megaset2', 'bunny').setOrigin(0);    
    });
    this.load.start();
}
```

## Additional Information

You can paste the example code here to have it run directly : https://labs.phaser.io/edit.html?src=src/textures\multi%20atlas.js

**Comment by photonstorm** [comment] 2019-09-30 12:36
This feels like a duplicate of #4330 to me. Will double-check when that issue is resolved.

**Comment by photonstorm** [comment] 2019-09-30 13:25
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed by photonstorm** 2019-09-30 13:25 UTC
Labels: 🕵️ Internal check needed

**Comment by TedGriggs** [comment] 2020-09-24 01:30
I am encountering the same issue with regular atlases:

this.scene.load.atlas("mykey", "/path.to/mykey.file"");

...loader says loaded and textures within atlas work.  Later:

this.scene.textures.remove("mykey"]);
this.scene.load.atlas("mykey", "/path.to/mykey.file"");

...loader says loaded and textures within atlas do not work.

**Comment by photonstorm** [comment] 2021-06-28 14:50
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/issue-trying-to-clear-texture-cache/9860/1
