### ISSUE TITLE
[.WebGL-0x7fa1c60b8c00]RENDER WARNING: there is no texture bound to the unit 2

### ISSUE THREAD

**Issue by actionmoon** [photonstorm/phaser#5482] opened 2021-01-01 01:29 UTC
## Version
* Phaser Version:3.50.0
* Operating system:Mac Pro
* Browser:Version 87.0.4280.88 (Official Build) (x86_64)

## Description
![phaser_waring](https://user-images.githubusercontent.com/6701451/103431995-cc438a00-4c13-11eb-8c36-5fd4621a0201.png)

I encountered this problem using this code below When you click the bear image in https://labs.phaser.io/edit.html !

## Example Test Code

```
class PreloadScene extends Phaser.Scene {
    constructor() {
        super({ key: 'PreloadScene' });
    }
    preload() {
        this.load.image('bunny', 'assets/sprites/bunny.png');
    }
    create() {
        console.log('PreloadScene')
        this.scene.start('GameMenuScene');
    }
}

class GameMenuScene extends Phaser.Scene {
    constructor() {
        super({ key: 'GameMenuScene' });
    }
    create() {
        console.log('GameMenuScene')
        var bunny = this.add.sprite(48, 102, 'bunny').setOrigin(0, 0).setDisplaySize(72, 72);
        bunny.setInteractive().on('pointerdown', () => {
            this.scene.start('GameScene');
        }, this);
        this.add.text(200, 100, 'Case shrugged.\nThe girl to his right giggled and nudged him.', { color: '#00ff00', align: 'left' });
    }
}

class GameScene extends Phaser.Scene {
    constructor() {
        super({ key: 'GameScene' });
    }
    create() {
        console.log('GameScene')
        this.add.sprite(48, 102, 'bunny').setOrigin(0, 0).setDisplaySize(72, 72);
    }
}

var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: [PreloadScene, GameMenuScene, GameScene]
};
var game = new Phaser.Game(config);
```

## Additional Information

If you comment the code below, it works well。
// this.add.text(200, 100, 'Case shrugged.\nThe girl to his right giggled and nudged him.', { color: '#00ff00', align: 'left' });

**Comment by photonstorm** [comment] 2021-01-01 16:55
Duplicate of #5464 - please track progress with that issue.

**Closed** 2021-01-01 16:55 UTC
