### ISSUE TITLE
Phaser stops working when the browser tab is inactive for a while

### ISSUE THREAD

**Issue by BeFiveINFO** [photonstorm/phaser#2009] opened 2015-08-17 16:22 UTC
I noticed in OSX Google Chrome (version 44.0.2403.155 (64-bit)) that Phaser stops working with the following error when the browser tab is inactive for a while. (The screen shows only a blank black screen.)
```
Uncaught TypeError: Cannot read property 'image' of undefined
```
The line with the error is in clearGLTextures, "for (var key in this.cache.image)"

Is there anyone that has come across the same issue?

**Comment by photonstorm** [comment] 2015-08-18 12:54
Sounds like the WebGL context is being destroyed by Chome. Not that I've ever seen it do this - anyone else?

**Comment by piecioshka** [comment] 2015-09-02 06:41
Yes! I was run only:
```
new Phaser.Game(800, 200, Phaser.Canvas, 'game');
```
next day I seen the same error message occur.

**Comment by BeFiveINFO** [comment] 2015-09-02 06:50
@piecioshka I have a question. Was your [disableVisibilityChange](http://phaser.io/docs/2.4.2/Phaser.Stage.html#disableVisibilityChange) set to true or false?
E.g. Did you set 
```javascript
game.stage.disableVisibilityChange = true;
```
I have not seen it for a while since I set disableVisibilityChange to false ([I think that it is set to false by default](https://github.com/photonstorm/phaser/blob/v2.4.2/src/core/Stage.js#L35)).

**Comment by piecioshka** [comment] 2015-09-02 06:55
No, I run only one line that I mention.

**Comment by piecioshka** [comment] 2015-09-02 14:32
@BeFiveINFO I was used your line, but it doesn't help me, a have the same error:

```
phaser.js:71831 Uncaught TypeError: Cannot read property 'image' of undefinedPhaser.Cache.clearGLTextures @ phaser.js:71831Phaser.Game.contextRestored @ phaser.js:38874
```

**Comment by BeFiveINFO** [comment] 2015-09-02 14:36
Thank you for the feedback. Then disableVisibilityChange might have little or nothing to do with it.

**Comment by photonstorm** [comment] 2015-09-14 10:30
So how long does it take before it destroys the context? If we're talking a day here then I'm honestly not sure it matters.

**Comment by BeFiveINFO** [comment] 2015-09-14 12:11
It varies. Sometimes it took only half an hour or maybe less. I notice that the problem can be seen also in [the example demos of the phaser site](http://phaser.io/examples).

I often keep example pages in a tab while searching for the forum on google and so on. I noticed that the phaser screen in the example pages sometimes (not always) goes black and stops working while it was inactive in background.

**Comment by photonstorm** [comment] 2015-09-14 12:48
It would be nice if it handled it gracefully, but I'm still not that bothered about the fact that it does actually happen. It's an edge case for sure.

**Comment by BeFiveINFO** [comment] 2015-09-14 12:53
Thank you for paying attention!
I will post findings as soon as I find anything else about the problem.

**Comment by photonstorm** [comment] 2016-02-04 15:32
Thank you for spending time to open this issue. I believe it has been discussed as far as it can be, and no immediate code change will be involved, so I'm closing it. Feel free to submit a PR if you feel you can resolve it in a clean and API friendly way.

**Closed by photonstorm** 2016-02-04 15:32 UTC
Labels: bug (phaser), feature request

**Comment by KupinFB** [comment] 2019-06-14 08:17
I believe that have the same problem. And i found a way how i can reproduce it.
I open my website where my app  on Mobile Chrome.
Then i switch applications on mobile device and return.
For example:
1) Open website
2) Switch app to Skype, switch to Camera then to .... (3 apps can be enough for my mobile)
3) Return to Chrome

![Screenshot_20190613-182459_Chrome](https://user-images.githubusercontent.com/8354925/59494412-bfc2d980-8e95-11e9-8725-c5d9f0cb3281.jpg)

If I switched too many apps and return, i see Chrome Refreshing.
If I switched not enough apps everything's okay
But between this conditions i see a bug with rendering.
I believe that it can be because of cleaning of memory by browser (but before browser automatic unloading from memory).

I can't find a way how to solve this problem...
Can you help me? ))
Thanks!
