### ISSUE TITLE
WEB_GL Bitmap mask with same image issue

### ISSUE THREAD

**Issue by JacobCaron** [photonstorm/phaser#4726] opened 2019-08-26 14:53 UTC
## Version

* Phaser Version: 3.18 - 3.19

* Operating system: Windows 10

## Description
When masking an image with the same image, WEB GL will throw many warnings and nothing will be rendered

## Example Test Code
```
var game = new Phaser.Game({
    parent: 'phaser-example',
    width: 640,
    height: 480,
    scene: {
        preload: preload,
        create: create
    }
});

function preload() {this.load.image('bunny', 'https://labs.phaser.io/assets/sprites/bunny.png');}

function create() {
	this.add.image(300, 200, "bunny").mask = new Phaser.Display.Masks.BitmapMask(this, this.add.image(200, 200, "bunny"));
}
```

**Comment by photonstorm** [comment] 2019-08-27 18:56
This is a duplicate of #4675 (your other issue), it's the same root cause.

**Closed by photonstorm** 2019-08-27 18:56 UTC
