### ISSUE TITLE
Phaser.GameObjects.Group.destroy() seems to be failing

### ISSUE THREAD

**Issue by DouglasLapsley** [photonstorm/phaser#3246] opened 2018-02-17 07:35 UTC
Possible bug in the API (Phaser 3.0.0)

```
this.balloonsArray = [];
...

generateBalloon() : void{
   let balloonGroup = this.add.group();
   balloonGroup.create(700, 100, 'misc', 'balloon';
   this.balloonsArray.push(balloonGroup);
}

update() : void{
    for(let x = 0; this.balloonsArray[x]; x++){
        let balloonGroup = this.balloonsArray[x];
        Phaser.Actions.IncX(balloonGroup.getChildren(), 1);
        if(balloonGroup.getChildren()[0].x > 750){
            balloonGroup.destroy();
            this.balloonsArray.splice(x, 1);
        }
    }
}

```
I would expect `ballonGroup` to be destroyed by `balloonGroup.destroy();` but it remains on screen.

So I wonder if the `Phaser.GameObjects.Group.destroy()` method is failing.

Thank you!

**Comment by agilul** [comment] 2018-02-17 11:41
From what I've seen on the source code, `Group.destroy()` only cleans up the group, clearing its `Set` of children gameobjects without calling `.destroy()` on them.

Maybe there can be added a `destroyChildren=false` parameter that if true also calls something like this on the children (or a new `Actions.Destroy`)?
```
Phaser.Actions.Call(this.children.entries, function(child) {child.destroy()});
```

**Comment by Ziao** [comment] 2018-02-18 14:37
AFAIK, this is by design. Phaser 3 avoids the parenting mess, and groups are merely ways to organize sprites together, so that you can run Actions on them, etc. Sprites are always children of the scene, so deleting a group should not delete the children.
I do agree with @agilul though, it would be nice if you could specify a boolean to force the removal of the group's children as well.

For now, one easy way is just to `baloonsGroup.getChildren().map(child => child.destroy())`, or similar.

I have also noticed a bug in your code: The for loop you use walks through the indices of balloonsArray, but as soon as you splice it, the indices change. If you are using ES6, a more elegant solution would be to use Array.reduce().

**Comment by photonstorm** [comment] 2018-02-19 23:02
As @Ziao said this is indeed by design, as unlike v2 Groups in v3 are not exclusive parents. A Sprite can exist in multiple Groups at the same time.

We could look at adding a `destroyChildren` argument, but in order for that to work, we'll have to change it so that Game Objects always emit a `destroyed` event, so that other Groups can listen for it and act accordingly. Which is probably a good idea anyway, as if you currently destroy a child of a Group, the Group doesn't know this has happened and will still include it in `getChildren` calls.

**Comment by DouglasLapsley** [comment] 2018-02-20 07:28
Thank you all very much.  Greatly appreciated.  I'll play some more with this.

So with regards parent > child relationships, would we just set the origin of all objects to the same co-ordinate and apply transforms to each object rather than have a parent child relationship and just transform the parent?

**Comment by Ziao** [comment] 2018-02-20 12:20
That's one way to do it. I did make a little something for people who can't
let go of the old parenting system. Sometimes it just makes more sense to
have groups behave the way they did in Phaser 2. Feel free to have a look.

https://github.com/Ziao/phaser3-interim-containers

**Comment by DouglasLapsley** [comment] 2018-02-20 12:39
Thanks very much :)

**Comment by photonstorm** [comment] 2018-03-27 00:10
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed** 2018-03-27 00:09 UTC
Labels: feature request

**Comment by satya4satyanm** [comment] 2020-07-25 04:43
baloonsGroup.getChildren().map(child => child.destroy())

This does not remove all children. removes only few and remaining are still live.

Please help
