### ISSUE TITLE
Phaser tag v2.6.0 game.physics.arcade.collide and overlap API example errors

### ISSUE THREAD

**Issue by Alicetech** [photonstorm/phaser#2613] opened 2016-07-10 21:25 UTC
I cant use arcade Physics with newest version.... This example is broken as of Phaser v2.6.0 http://phaser.io/examples/v2/arcade-physics/group-vs-group

Phaser v2.5.0  works fine

How to reproduce:
Hit space. Example locks up. Console shows error:
phaser.2.6.0.min.js:24 Uncaught TypeError: Cannot set property 'x' of undefined

All browsers produce the same error:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0

Can anyone else reproduce? Was this not unit tested? Can you please put a defect notice for others on the examples page.....

**Comment by drhayes** [comment] 2016-07-10 22:48
Dupe of #2610?

**Comment by fariazz** [comment] 2016-07-11 02:27
I'm experiencing the game breaks when you check collision between a sprite and a group.

Made a Codepen with the essential to show: https://codepen.io/fariazz/pen/zBEmvY

It worked fine in 2.5

**Comment by photonstorm** [comment] 2016-07-11 09:16
This is fixed in the 2.6.1 release which was published just now.

**Closed by photonstorm** 2016-07-11 09:16 UTC

**Comment by Alicetech** [comment] 2016-07-11 16:59
Thank you @photonstorm . But one question remains. Is there any unit testing? If not, for us to trust the Phaser API we would have to fork and put unit testing on all functions we use.

**Comment by photonstorm** [comment] 2016-07-11 18:42
No, afraid not. Full unit test coverage of Pixi and Phaser is a chimera.

**Comment by fariazz** [comment] 2016-07-11 22:34
Thanks for the fix @photonstorm !
