### ISSUE TITLE
window.onblur only if the browser doesn't support visibilitychange

### ISSUE THREAD

**Issue by austinhallock** [photonstorm/phaser#1620] opened 2015-02-12 21:44 UTC
We're running into a very weird bug that seems to be limited to iOS webviews (presumably anything UIWebView, but not WKWebView).

We load up an interstital ad above a game in Phaser, which includes an "x" button. When that "x" button is tapped, the webview fires an onfocus event (this _may_ be because the interstitial ad loads in an iframe which could steal the focus - though `document.hidden` is still false). When the game is tapped, the webview fires an onblur event (super weird) which ends up pausing the game (thinking the page is inactive).

If we just set `window.blur = null` after phaser sets it, it fixes it.

https://github.com/photonstorm/phaser/blob/6c7c0cb1b62b8ea4c1808efde62aff6840ca3099/src/core/Stage.js#L244

This is a weird bug, but it seems like an easy fix is to only fallback to the onpagehide, onpageshow, onblur and onfocus if the visibilitychange event isn't supported.

FYI the game this is happening in is http://dontcross.clay.io - but this may be fixed by the time anyone looks at this since we're talking with Eugene about it.

**Comment by photonstorm** [comment] 2015-02-18 23:34
I can't just ignore window.blur / focus if the page visibility API is available because they do two different things. If you give focus to another window for example, the pv API doesn't handle that, so the game can't pause should you say click out onto twitter for a second, then back in again.

I've been reading but I can't find a way to determine if the onblur was caused by an iframe or not. It still seems to signal it on a window level, there doesn't appear to be document.onblur (that actually works). So unless you can find a work-around I'm sadly going to have to flag this as "can't fix".

**Comment by photonstorm** [comment] 2015-07-08 13:14
Closing this off as a still annoying browser bug.

**Comment by micsun-al** [comment] 2016-09-21 22:30
This seems to reproduce with the Phaser 2.6.2 on iOS/Safari 10.

Here is a potential fix:

`/**
* Starts a page visibility event listener running, or window.onpagehide/onpageshow if not supported by the browser.
* Also listens for window.onblur and window.onfocus.
* 
* @method Phaser.Stage#checkVisibility
*/
Phaser.Stage.prototype.checkVisibility = function () {
    if (document.hidden !== undefined)
    {
        Phaser.visibilityHidden = 'hidden';
        this._hiddenVar = 'visibilitychange';
    }
    else if (document.webkitHidden !== undefined)
    {
        Phaser.visibilityHidden = 'webkitHidden';
        this._hiddenVar = 'webkitvisibilitychange';
    }
    else if (document.mozHidden !== undefined)
    {
        Phaser.visibilityHidden = 'mozHidden';
        this._hiddenVar = 'mozvisibilitychange';
    }
    else if (document.msHidden !== undefined)
    {
        Phaser.visibilityHidden = 'msHidden';
        this._hiddenVar = 'msvisibilitychange';
    }
    else
    {
        this._hiddenVar = null;
    }

    var _this = this;

    this._onChange = function (event) {
        return _this.visibilityChange(event);
    };

    //  Does browser support it? If not (like in IE9 or old Android) we need to fall back to blur/focus
    if (this._hiddenVar)
    {
        document.addEventListener(this._hiddenVar, this._onChange, false);
    }

    window.onblur = this._onChange;
    window.onfocus = this._onChange;

    window.onpagehide = this._onChange;
    window.onpageshow = this._onChange;
    
    if (this.game.device.cocoonJSApp)
    {
        CocoonJS.App.onSuspended.addEventListener(function () {
            Phaser.Stage.prototype.visibilityChange.call(_this, { type: "pause" });
        });

        CocoonJS.App.onActivated.addEventListener(function () {
            Phaser.Stage.prototype.visibilityChange.call(_this, { type: "resume" });
        });
    }

};

/**
* This method is called when the document visibility is changed.
* 
* @method Phaser.Stage#visibilityChange
* @param {Event} event - Its type will be used to decide whether the game should be paused or not.
*/
Phaser.Stage.prototype.visibilityChange = function (event) {
    if(typeof document[Phaser.visibilityHidden] === 'undefined'){
        if (event.type === 'pagehide' || event.type === 'blur' || event.type === 'pageshow' || event.type === 'focus')
        {
            if (event.type === 'pagehide' || event.type === 'blur')
            {
                this.game.focusLoss(event);
            }
            else if (event.type === 'pageshow' || event.type === 'focus')
            {
                this.game.focusGain(event);
            }

            return;
        }
    }
    else
    {
        if (document[Phaser.visibilityHidden] && (event.type === 'pagehide' || event.type === 'blur'))
        {
            this.game.focusLoss(event);
            return;
        }
        else if (!document[Phaser.visibilityHidden] && (event.type === 'pageshow' || event.type === 'focus'))
        {
            this.game.focusGain(event);
            return;
        }
    }

    if (this.disableVisibilityChange)
    {
        return;
    }

    if (document.hidden || document.mozHidden || document.msHidden || document.webkitHidden || event.type === "pause")
    {
        this.game.gamePaused(event);
    }
    else
    {
        this.game.gameResumed(event);
    }

};`

**Comment by photonstorm** [comment] 2017-04-20 12:30
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. If the problem persists, please open an issue on the Phaser CE repo.

**Closed by photonstorm** 2017-04-20 12:30 UTC
Labels: bug (browser)
