### ISSUE TITLE
Camera.shake

### ISSUE THREAD

**Issue by VitaZheltyakov** [photonstorm/phaser#2617] opened 2016-07-11 22:08 UTC
This Issue is about (delete as applicable)

* A bug in the API
--
camera.shake - shake all sprites in the view.
We need a parameter, which forbade sprite shake. For example, sprite.noShake = true;

**Comment by photonstorm** [comment] 2016-07-11 22:16
This is a feature request, not a bug.

**Comment by photonstorm** [comment] 2016-09-26 20:58
I'm closing this off as a "won't do". Camera shake is implemented (in WebGL) by changing the projection offset at the start of the render, not by adjusting sprite coordinates or similar. It would need refactoring to provide this feature, which I don't want to do at this stage.

**Closed by photonstorm** 2016-09-26 20:58 UTC
Labels: feature request
