### ISSUE TITLE
Alpha of Container doesn't work for the children

### ISSUE THREAD

**Issue by laineus** [photonstorm/phaser#4916] opened 2019-12-19 15:11 UTC
## Version

* Phaser Version: 3.20.1

* Operating system: Ubuntu 18.04

* Browser: Google Chrome 79.0.3945.79

## Description

Version 3.20 ~

Children can not be applied alpha of parent Container.

## Example Test Code

- 3.19.0 https://codepen.io/laineus/pen/yLLqBOO
- 3.20.1 https://codepen.io/laineus/pen/JjjZgqJ

## Additional Information

PR: https://github.com/photonstorm/phaser/pull/4915

**Comment by photonstorm** [comment] 2019-12-28 17:06
Looking at this further, the issue isn't actually anything to do with Container children. The actual bug is that Shape objects, despite having the quad alpha component, cannot use quad alpha values. If you set them, all alpha values are ignored. It looks like this has never worked, which makes sense in a way, because Shapes are not quads (rectangles are, but that's all).

The following shows what I mean:

```js
var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('sky', 'assets/skies/sky4.png');
}

function create ()
{
    const bg = this.add.sprite(0, 0, 'sky').setOrigin(0, 0);

    const rect = this.add.rectangle(110, 110, 200, 200, 0xFF0000, 1);

    rect.setAlpha(0.1, 0.1, 0.5, 0.5);
}
```

Now, change `setAlpha` to just `setAlpha(0.5)` and it'll work fine. This is the real root of the issue.

**Comment by laineus** [comment] 2019-12-28 17:24
I understood.
Thank you for the investigation and explanation.

**Comment by photonstorm** [comment] 2019-12-28 17:29
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed** 2019-12-28 17:29 UTC
Labels: 🐛 Bug
