### ISSUE TITLE
Bug when setting alpha values for a sprite inside container

### ISSUE THREAD

**Issue by MrcSnm** [photonstorm/phaser#4714] opened 2019-08-19 04:03 UTC
## Version 3.19 and lower

* Phaser Version: 3.19

* Operating system: Windows 10x64

* Browser: Chrome

## Description
Setting the alpha topLeft, topRight, botLeft, botRight alpha values on a sprite inside a container will cause the command being ignored, so, calling setAlpha(1, 1, 0, 0) on these sprites will do nothing

## Example Test Code ->  (Code Took and modified from phaser3 examples container alph)

```
   var image0 = this.add.image(0, 0, 'lemming');
    var image1 = this.add.image(-100, -100, 'lemming');
    var image2 = this.add.image(100, -100, 'lemming');
    var image3 = this.add.image(100, 100, 'lemming');
    var image4 = this.add.image(-100, 100, 'lemming');
    container = this.add.container(400, 300, [ image0, image1, image2, image3, image4 ]);
    image1.setAlpha(0, 0, 1, 1);

```
## Additional Information
When calling with the four parameters, it will just make the sprite opaque

**Comment by photonstorm** [comment] 2019-08-19 10:42
Yes, this is a known limitation of Containers. I have no immediate plans to change this, although I would happily accept a non-invasive PR that did so.

**Comment by MrcSnm** [comment] 2019-08-19 15:00
What would be a non invasive pr? I could fix this but I don't know how where the render call really happens, it is quite hidden you know, how can I find the render call

PS: can update on the documentation that this don't work? I lost some time trying to find if it were bug on my code

**Comment by photonstorm** [comment] 2019-08-19 15:09
The WebGL render call for a Container is made in the not-so-hidden file [ContainerWebGLRenderer](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/container/ContainerWebGLRenderer.js).

The issue is where the Container alpha is multiplied by the Child alpha, so that changing the alpha of a container impacts children. It uses the global alpha value, not the per-vertex one. A non-invasive PR means one that replicates this functionality unless per-vertex alpha has been used.

**Comment by MrcSnm** [comment] 2019-08-19 16:28
I made the new pull request

**Comment by photonstorm** [comment] 2019-10-02 09:10
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.

**Closed by photonstorm** 2019-10-02 09:10 UTC
Labels: 🐛 Bug, 👎Won't Fix
