### ISSUE TITLE
SpinePlugin throws error while unloading and restart game

### ISSUE THREAD

**Issue by ayamomiji** [photonstorm/phaser#5477] opened 2020-12-28 17:45 UTC
## Version

* Phaser Version: 3.50.1
* Operating system: MacOS 11.1

## Description

When using `game.destroy` with SpinePlugin, Phaser throws `Uncaught TypeError: this.systems is null` from SpinePlugin's shutdown method.
The game cannot restart again, Phaser throws `Uncaught TypeError: atlasCache is undefined` on load spine model.

## Example Test Code

```
function createGame() {
  new Phaser.Game({
    type: Phaser.AUTO,
    plugins: {
      scene: [
        { key: 'SpinePlugin', plugin: window.SpinePlugin, mapping: 'spine' }
      ]
    },
    scene: {
      preload() {
        this.load.setPath('skeletons/')
        this.load.spine('character', 'character.json', 'character.atlas')
      }
    }
  })
}
createGame()

setTimeout(() => game.destroy(true, false), 2000) // Uncaught TypeError: this.systems is null
setTimeout(createGame, 4000) // Uncaught TypeError: atlasCache is undefined
```

**Comment by marek-charactr** [comment] 2021-01-14 19:23
any news on this? got the same problem

**Comment by photonstorm** [comment] 2021-01-15 09:23
If there was news there would have been a comment / related git commit here. Feel free to try and fix it and issue a PR if it's a high priority for you.

**Comment by Pong420** [comment] 2021-02-13 00:17
https://github.com/photonstorm/phaser/blob/d67c93646cbfe8ba5997954f8af29a8f3f9e8e91/plugins/spine/src/SpinePlugin.js#L415-L420

The root cause should be `SpinePlugin#destroy` call twice ?
`destroy` event from `Phaser.Scenes.Systems` and and `SpinePlugin#gameDestroy `

**Comment by photonstorm** [comment] 2021-03-01 16:27
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed by photonstorm** 2021-03-01 16:27 UTC
Labels: 🐛 Spine
