### ISSUE TITLE
world X, worldY unexpected position offset when canvas element is fullscreen

### ISSUE THREAD

**Issue by the-simian** [photonstorm/phaser#4147] opened 2018-11-05 20:27 UTC
* Phaser Version:  3.15.1 (latest)
* Operating system: Windows 64 bit
* Browser: Chrome (but might affect others?)

## Description
When I am tracking the mouse position, there is some unexpected behavior with the wolrdX and world Y values

When the browser   is exactly sized things behave correctly: 
![expected](https://user-images.githubusercontent.com/954596/48024329-008b9080-e106-11e8-91c0-6cdaf5103a34.gif)

When the browser is enlarged one way or the other, there's an unexpected offset:
![unexpected](https://user-images.githubusercontent.com/954596/48024508-74c63400-e106-11e8-9354-21f7d557c316.gif)

## Example Test Code

css: 
```css
canvas {
    width: 100% !important;
    height: 100% !important;
    object-fit: contain;
}
```

js: 
```js
createcircle() {
     //make circle and graphics to draw it.
    this._c = this._c || 
                  new Phaser.Geom.Circle(200, 300, 4);
   
     this._cGraphics = this._cGraphics || 
                                this.scene.add.graphics({lineStyle: { color: 0xff0000 }});

    const game = this.scene.game;

    //  keep track of pointer
    const { worldX, worldY } = game.input.mousePointer;
    this._c.setPosition(worldX, worldY);

    if (game.input.mousePointer.isDown) {
      //draw when mouse is down
      this._c.clear();
      this._cGraphics.strokeCircleShape(this._c);
    }
}

update {
    this.createcircle();
}
```

## Additional Information

Its very likely I'm just using the wrong property, but I am wondering if this is the right approach to detecting the mouse position in a game world or not. I do get that the canvas itself might be expanding to the browser height so the input events do not match the game world. If I use the x and y though, the red circle does not appear in the right place at all.

**Comment by samme** [comment] 2018-11-06 00:58
#3666

**Comment by the-simian** [comment] 2018-11-06 16:09
@samme I searched around and actually didn't see this issue from before. Reading there makes me thing this is 'unfixable' (maybe?) should I close this or keep it open @photonstorm ?

I appreciate the followup

**Comment by samme** [comment] 2018-11-09 02:54
I think the upcoming ScaleManager may [handle this case](http://labs.phaser.io/edit.html?src=src\scalemanager\contain.js).

**Comment by the-simian** [comment] 2018-11-09 18:29
Might make sense to leave this open until then, and close it when that releases. I'll update my scaffold to use ScaleManager out of the box

**Comment by xaroth8088** [comment] 2020-07-20 23:56
This is probably happening because the switch to full-screen isn't causing scaleManager to re-calculate the pointer offsets.  One can see this by moving the canvas's parent around on the page (without resizing it).

The workaround appears to be to update the scale manager's bounds via `this.scale.updateBounds()` immediately after the fullscreen change happens, or whenever the parent container changes position in the DOM.  Note that this happens automatically if ScaleManager detects that the canvas size has changed, hence the note about not resizing it to get the reproduction case.

A related workaround for mouseDown events where one doesn't have a good hook from which to call `updateBounds()` is to cause Phaser to re-calculate the pointer position in one's `pointerdown` handler, like so:

```
this.input.on('pointerdown', (pointer) => {
  this.scale.updateBounds();
  pointer.down(pointer.event);
  pointer.updateWorldPoint(this.cameras.main);
  // ... the rest of the click hander
});
```

As far as a long-term fix on the Phaser side, there appears to me to be two obvious avenues to explore, though someone with more experience in the codebase could probably suggest better ones:

1. Call `updateBounds()` any time there's a mouse event.  This feels like it might be a problem performance-wise, but it would be the "safest" option, and might enable some DOM listeners in ScaleManager to be removed.

2. Instead of using `event.pageX/Y` and then doing math to find the bounds of the canvas, use [event.offsetX/Y](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX).  While _technically_ this event property is marked as "experimental", [CanIUse](https://caniuse.com/#search=offsetx) lists it as well supported across all browsers.  Implementing this is probably a bit more work - especially to ensure that the offset value is coming from the appropriate DOM element - but it would likely reduce complexity elsewhere.

Hope that helps!

**Comment by samme** [comment] 2020-07-21 20:05
I don't think this problem exists in the current Phaser.

**Comment by embeddedt** [comment] 2020-08-05 15:06
Out of the box, I seem to still have this issue with Phaser 3.24.1. Calling `this.scale.updateBounds()` after `this.game.scale.startFullscreen()` appears to fix the problem.

**Comment by samme** [comment] 2020-08-05 16:47
380cc422b2c6f7a286db0db3751922d5a6c06543

**Comment by photonstorm** [comment] 2020-09-11 11:14
Sorry for leaving this open for so long, but have re-tested it against 3.50 and it's still working, so happy to close this one off.

**Closed by photonstorm** 2020-09-11 11:14 UTC
Labels: ⌨️ Input, 🖥️ Scale Manager
