### ISSUE TITLE
Group hash growth unbounded?

### ISSUE THREAD

**Issue by strawlion** [photonstorm/phaser#2232] opened 2015-11-27 19:19 UTC
Hey All, I noticed that when moving a sprite from one group to another via the add call, it's not removed from the original group's hash. Is this intended?

IE (pseudo code)
```javascript
var sprite = someSprite;

groupOne.add(sprite);
// groupOne.hash === [sprite]
// groupTwo.hash === []

groupTwo.add(sprite);
// groupOne.hash === [sprite]
// groupTwo.hash === [sprite]
```

This is with V2.4.3

**Comment by strawlion** [comment] 2015-11-27 19:20
FWIW, I'd be happy to submit a fix along with tests here if it's a real issue

**Comment by McIntozh** [comment] 2016-01-06 22:23
Yes, I can confirm this for 2.4.4 too.
Group hash grows and hold references to already destroyed sprites, causing memory leaks.

But this only happens when the sprite has a physics body:

```
var group1;
var group2;
function create() {
    game.physics.startSystem(Phaser.Physics.P2JS);
    group1 = game.add.group();
    group2 = game.add.group();

    var sprite=game.add.sprite(0,0);
    game.physics.p2.enable(sprite);
    console.log("Should return false: "+(group1.hash.indexOf(sprite)>=0));
    
    group1.add(sprite);
    console.log("Should return true: "+(group1.hash.indexOf(sprite)>=0));
    
    group2.add(sprite);
    console.log("Should return false: "+(group1.hash.indexOf(sprite)>=0));
}
```

Workarounds:
1) Remove the child from the original group before adding it to another group
2) Call `if (this.parent && this.parent.remove)this.parent.remove(this);` before adding to a group

Suggested Bugfix:
The reason for this bug is, that `add` calls `this.addChild` (Line 31402 in phaser.js) wich removes the sprite from the children of its parent sprite. But because this is in PIXI code, `removeFromHash` is not called. Perhaps this should be called before `addChild`.

**Comment by photonstorm** [comment] 2016-02-03 21:51
This is now fixed in dev.

**Closed by photonstorm** 2016-02-03 21:51 UTC
