### ISSUE TITLE
Resize/Fit to Screen Issue in Phaser 3.13.0

### ISSUE THREAD

**Issue by hsan999** [photonstorm/phaser#4076] opened 2018-09-30 19:03 UTC
Version 3.13.0

First things first, thank you for the Facebook Instant Games Plugin!

I got right into using it over the weekend, but ran into some stubborn fit to to screen issues.  Perhaps this is not a bug but just something I need to handle differently in the new version.

I upgraded to Phaser 3.13.0 over the weekend and all worked fine except that now my game is not resizing properly (I am simply stretching to fit).  I have attached screenshots.  I have narrowed it down to the phaser.min.js file in the new version that is causing the change (NOT phaser-facebook-instant-games.min.js).  The version from Phaser 3.11 fits appropriately to screen.  I'd really like to try out the new Facebook Instant Games features (working great so far!  Thank you!) but unfortunately this fill screen thing is probably going to keep me from moving forward.

This is the only code used to resize, and it works flawlessly in 3.11

`<style type="text/css">
        html, body {
          margin: 0;
          padding: 0;
          background: blue;
          height: 100%;
          width:100%;
          object-fit:fill;
        }
        canvas {
          width: 100%;
          height: 100%;
          background: red;
          object-fit:fill;
          display:block;
        }

        </style>`

This is the phaser config stuff.

`
var stageWidth = 1600;
var stageHeight = 900;
var config = {
              type: Phaser.AUTO,
              width: stageWidth,
              height: stageHeight,
              physics: {
                default: 'arcade',
                arcade: {
                  gravity: { y: 300 },
                  debug: false
                }
              },
              scene: [...]
          };

          var game = new Phaser.Game(config);`

Here are some screenshots demonstrating the difference in Chrome.  Similar (just slightly diff size) behavior occurs in Mozilla and IE.

![example1](https://user-images.githubusercontent.com/43729637/46261402-aff69700-c4b8-11e8-906e-d76b74cf5b1b.PNG)

![example2](https://user-images.githubusercontent.com/43729637/46261406-bd138600-c4b8-11e8-9702-f649a3293a2e.PNG)

**Comment by photonstorm** [comment] 2018-10-01 08:48
Thank you for taking the time to open this issue. However, it's a duplicate of #4066, so to keep things tidy I'm going to close this issue. Please track bug progress on the original issue.

**Closed by photonstorm** 2018-10-01 08:48 UTC
