### ISSUE TITLE
Arc on High DPI screen creates strange line from top left corner

### ISSUE THREAD

**Issue by Brandoning** [photonstorm/phaser#4021] opened 2018-09-10 14:59 UTC
**Phaser Version:** 3.12.0
**Browser :** Chrome Android / Samsung Internet Android
**OS:** Android (latest, Galaxy S7)
_Can't replicate this in a desktop browser, or inspect element Chrome_

![screenshot_20180910-154742_chrome](https://user-images.githubusercontent.com/5629295/45305870-271cb900-b513-11e8-9ca9-881b3753c266.jpg)

**Example Code:**
```
this.timer--;

        var perc = (this.timer / this.maxTime) * 100;
        var real = Math.round((360 / 100) * perc);

        if( this.timerGraphics ) this.timerGraphics.destroy();
        this.timerGraphics = this.add.graphics();
        this.timerGraphics.lineStyle((3 * this._GAME.newScale), 0xffffff, 1);
        this.timerGraphics.beginPath();
        this.timerGraphics.arc((975 * this._GAME.newScale), (555 * this._GAME.newScaleH), (25 * this._GAME.newScale), Phaser.Math.DegToRad(0), Phaser.Math.DegToRad(real), false, 0.01);
        this.timerGraphics.strokePath();
        this.timerGraphics.closePath();

        // Create timer BG
        this.timerGraphics.beginPath();
        this.timerGraphics.fillStyle(0xffffff, 0.21);
        this.timerGraphics.arc((975 * this._GAME.newScale), (555 * this._GAME.newScaleH), (25 * this._GAME.newScale), Phaser.Math.DegToRad(0), Phaser.Math.DegToRad(360), false, 0.01);
        this.timerGraphics.closePath();
        this.timerGraphics.fillPath();

        this.timerGraphics.setDepth(52); 

```

this._GAME.newScale + newScaleH is calculated from the below, pretty standard to allow responsive scaling:

        // Figure scale less than 1024
        this.gameWidth = gameWidth * window.devicePixelRatio;
        this.gameHeight = gameHeight * window.devicePixelRatio;
        this.newScale = (gameWidth / 1024) * window.devicePixelRatio;
        this.newScaleH = (gameHeight / 600) * window.devicePixelRatio;

I've attempted to round the integer too to avoid strange calculations, but this hasn't helped and the same line appears from the top left to the arc.

Please advise if this is a known issue, if I'm doing something wrong or if this is a new bug.

**Comment by photonstorm** [comment] 2018-09-10 16:32
Please try this on 3.13 (current master branch) because I added a fix specifically for this in there.

**Comment by alexeymolchan** [comment] 2018-09-10 16:38
i think its the same issue that i have with a strokeRoundedRect

**Comment by Brandoning** [comment] 2018-09-11 08:57
Thanks for your response but I'm still seeing the same issue on the master branch. For context, here's my Phaser config:

```
{
            type: Phaser.AUTO,
            //pixelArt: true,
            //roundPixels: true,
            parent: 'game',
            antiAlias: true,
            width: gameWidth * window.devicePixelRatio,
            height: gameHeight * window.devicePixelRatio,
            physics: {
                default: 'arcade',
                arcade: {
                    gravity: { y: 0, x: 0 },
                    debug: false
                }
            },
            // Games
            scene: [
                GameOne,
                GameTwo,
                GameThree,
                GameFour
            ],
            plugins: {
            
            }
        };
```

And the arc is updated through this timer (where the code for incrementTimer is in my original post):

```
this.incrementTimerTimer = this.time.addEvent({
            delay: 1000,
            callback: this.incrementTimer,
            callbackScope: this,
            repeat: (this.maxTime - 2)
        });
```

And my updated Phaser line from package.json, I made sure to rebuild after this and clear the device cache:
`
    "phaser": "github:photonstorm/phaser#master",
`

**Comment by Brandoning** [comment] 2018-09-11 10:04
@alexeymolchan Do you have an example or issue # for that bug? So I can do some further testing

**Comment by Brandoning** [comment] 2018-09-26 15:45
I managed to prevent this issue from occurring. Not sure if it's a bug in the core, maybe you can advise.

**Buggy Code**
```
     if( this.timerGraphics ) this.timerGraphics.destroy();
        this.timerGraphics = this.add.graphics();
        this.timerGraphics.lineStyle((3 * this._GAME.newScale), 0xffffff, 1);
        this.timerGraphics.beginPath();
// below line is the issue
        this.timerGraphics.arc((975 * this._GAME.newScale), (555 * this._GAME.newScaleH), (25 * this._GAME.newScale), Phaser.Math.DegToRad(0), Phaser.Math.DegToRad(real), false, 0.01);
        this.timerGraphics.strokePath();
        this.timerGraphics.closePath();
```

**Fixed Code**
    ```
    if( this.timerGraphics ) this.timerGraphics.destroy();
        this.timerGraphics = this.add.graphics();
        this.timerGraphics.lineStyle(3 * this._GAME.newScale, 0xffffff, 1);
        this.timerGraphics.beginPath();
// below line is the issue
        this.timerGraphics.arc(0, 0, (25 * this._GAME.newScaleH), Phaser.Math.DegToRad(0), Phaser.Math.DegToRad(real), false, 0.01);
        this.timerGraphics.strokePath();
        this.timerGraphics.closePath();

```

On the .arc command you must set it to 0,0 for x,y central positions (first two arguments), then use setX and setY to move it to where you want.

This is strange because the "broken" code is actually not broke in things other than high DPI devices.  But the fixed code displays it correctly for all devices regardless.

Hopefully this helps in diagnosing the issue with this and the other referenced bug above.

Thanks,
Brandon

**Comment by photonstorm** [comment] 2020-08-26 10:01
Sorry for leaving this issue lingering for so long, am going to close it as it's a duplicate of #3955 (same root cause), so I'll follow-up in there.

**Closed by photonstorm** 2020-08-26 10:01 UTC
Labels: 🙇‍♂️ User to test
