### ISSUE TITLE
Very Weird Phaser Bug

### ISSUE THREAD

**Issue by McFarts** [photonstorm/phaser#2121] opened 2015-10-02 18:41 UTC
Not sure what is going on, but sometimes when you refresh everything is all smooth and works like butter. But then sometimes when u refresh everything is all glitchy, and laggy? It does this on the latest chrome and opera and Firefox. 

I've made a video to try to explain, although you cannot really tell because the screen recorder is shit and tears the screen too, but it's much noticeable on my side.

https://www.youtube.com/watch?v=8_j1T6Zauec&feature=youtu.be

And yes, it does this without recording the screen.

Okay. (Code is in the examples below)

I didn't add my graphics  (copyright issues atm)

But, in any event you can still see the lag when moving on certain refreshes, it's very noticeable.

http://codepen.io/anon/pen/dYvWaL

Edit: Especially the blinking is very visible on certain refreshes.. Really weird..

Edit: JSfiddle:
https://jsfiddle.net/Dillybob/rzL43vqf/

**Comment by pnstickne** [comment] 2015-10-02 19:34
Does the observed performance behavior change between different versions of Phaser? 

Usually such jumps are caused by GC or other resource cleanup; it also takes some time for browsers to collect stats and optimize/jit code.

**Comment by McFarts** [comment] 2015-10-02 19:43
Not that I know of, I was using an older version before I upgraded to the recent because I thought it could be the issue.

Nah the weird lag / glitchy effect stays after the refresh until another refresh. Sometimes I will get a good refresh and it works smooth as butter, and sometimes the total opposite.

**Comment by pnstickne** [comment] 2015-10-02 19:46
Curious, I would not expect the lab to persist.

**Comment by McFarts** [comment] 2015-10-02 20:00
Okay.

I didn't add my graphics  (copyright issues atm)

But, in any event you can still see the lag when moving on certain refreshes, it's very noticeable.

http://codepen.io/anon/pen/dYvWaL

**Comment by McFarts** [comment] 2015-10-02 20:14
Sorry for the double post, but this is important.

As you said, you wouldn't expect the lag to persist, which is true because on some refreshes you can see the text blink for like 500ms then it stops everything becomes smooth/rendered.

But, I think I can narrow down the bug more, it's right after that certain 300-500ms of blinking, it doesn't stop and just continues.   Hope this helps? Not sure I have no where to start as I'm trying to convert my dom game to phaser, not versed in phaser at all :(

**Comment by drhayes** [comment] 2015-10-02 20:19
Are you still seeing it if you change the renderer to Phaser.CANVAS? Are you still seeing it if you take the debug text out of the render method? (try separately, try on a different computer)

**Comment by McFarts** [comment] 2015-10-02 20:33
@drhayes 

Removing the text doesn't make a difference.

Changing the renderer to Phaser.CANVAS does fix the glitchyness but my animations are all very glitchy still.

Changing the renderer to `Phaser.WebGL` makes my animations very smoother but only works on a certain refresh.

So bug is isolated now for rendering under Phaser.WebGL, (if this is related to Phaser?) If not, it's probably a WebGL issue.

**Comment by pnstickne** [comment] 2015-10-02 20:37
FWIW: I am not seeing the behavior in Android Chrome - here it always runs terrible at the start (I think it might be breaking through the frame skip) and then settles down. The codepen version appears to start with worse performance.

**Comment by photonstorm** [comment] 2015-10-03 09:50
Actually I've seen this happen as well. It never happens on my PC, but on my Macbook Pro it's pretty consistent and will happen about 1 in 2 refreshes, it doesn't matter if it's canvas or webgl either.

There are two separate issues. One is when the updateLogic fires but with no render call. This has the effect of calling preUpdate on all subsystems. In some cases that blanks them - for example the Debug class's preUpdate erases the canvas it uses entirely. If render is then skipped it causes the Debug canvas to be blank for a single frame, usually coming back again in the next one. But it causes a 'flickering' effect (as it happens so quickly).

The second issue is with the frame skip logic on some systems. The actual concept behind the frame skip code is sound, and based on industry 'best practises'. However I'm pretty certain what happens is that the browser struggles at the start, most likely due to the large gc sweep that happens, but then is constantly 'behind' where the frame skip expects it to be. I think this picture from the [Game Design Patterns](http://gameprogrammingpatterns.com/game-loop.html) book sum's it up well:

![balls](http://gameprogrammingpatterns.com/images/game-loop-timeline.png)

I'm pretty certain that what happens is the timer gets thrown out early on, so is in a constant never-ending state of 'catch up', doing double updates and no renders constantly, causing the effect we're seeing.

On my Macbook if I do 'Game.forceSingleUpdate = true' then it runs smooth as butter every time. On my PC it doesn't need it. On a slow device that can be quite dangerous, so it's sort of a 'middle ground' area where it's a problem.

**Comment by McFarts** [comment] 2015-10-03 10:25
> it doesn't matter if it's canvas or webgl either. That's odd. For my PC, (Win 7, 64 bit), fx 6300, gtx 460 hawk (if this matters), it only does it when the game is rendered in webgl. I tried it when the renderer was set to Canvas and it works fine but the tweening and some animations are not as smooth (why I love the webgl).


Edit: Wow, I added 
```
function update(){
	game.forceSingleUpdate = true
}
```

and I'm using `Phaser.WebGL` and it's working 100% now as well.  Thanks for that. I'll update my thread on the html5dev forums.

**Comment by photonstorm** [comment] 2016-02-04 13:36
Closing this one off as there's no clear-path to doing anything more for it, without rewriting how Phaser works internally (which is what Lazer is all about).

**Closed by photonstorm** 2016-02-04 13:36 UTC
