### ISSUE TITLE
Bitmap data in webgl

### ISSUE THREAD

**Issue by cscott5288** [photonstorm/phaser#1778] opened 2015-05-04 16:03 UTC
I ran into an issue when trying to convert the entire canvas into an image, then drawing it to a bitmap data object:

var bmd = game.add.bitmapData(150, 150);
bmd.copy(game.canvas,0,0,game.width,game.height,0,0,150,150); 
var miniMap = bmd.addToWorld(300,300);

The code works fine when you force the came into Phaser.Canvas mode. But it doesn't work at all when Phaser is using webgl. It doesn't say in the docs that Phaser needs to be in canvas mode if you pass it a canvas element as the source parameter. If this is the case, should it be reflected in the docs?

Also, is there anyway to achieve the effect of passing the canvas and copying it while Phaser is in webgl mode? Any hacks/suggestions? I suspect it's because getImageData() doesn't work on a webgl context.

**Comment by photonstorm** [comment] 2015-05-04 17:46
Phaser doesn't need to be running in Canvas mode in order for a BitmapData to render a canvas to itself. What it does is take the canvas, extract the 2d context from it and then draws that. The problem is that in a WebGL game there isn't anything on the 2d context, it's blank. You can render a WebGL canvas to another canvas if it was created with `preserveDrawingBuffer` enabled, which you could do, but it can harm performance as well, so is a trade off.

**Comment by cscott5288** [comment] 2015-05-04 18:08
Thanks a lot Richard. It works perfectly with  preserveDrawingBuffer. I'm not sure how much that will hinder performance, but it seems to be unaffected (i'll do more rigorous testing later). 

Now my only problem is that it only seems to be able to copy the visible portion of the canvas. Is there anyway to capture the entire game.world and not just the portion visible in the window? I'm using the same code as above.

**Comment by cscott5288** [comment] 2015-05-04 18:33
Okay, so I figured out that if I don't scale the canvas while drawing/copying, I can capture the entire thing (including non-visible portions) in bitmap data.

No all I need to do is figure out how to scale down the bitmap data object! I can see that there is a method for resize:http://phaser.io/docs/2.3.0/Phaser.BitmapData.html#resize

Doesn't seem to work though if I pass it a width/height.

**Comment by cscott5288** [comment] 2015-05-04 18:43
That's interesting. If I convert the bmd to an image (so I can scale it), it will only show the portion of the bitmap data which was visible. 

       var bmd = game.add.bitmapData(game.width, game.height);
        bmd.copy(game.canvas, 0, 0, game.width, game.height, 0, 0, null, null, 0, 0, 0);
        var image = game.add.image(200, 200, bmd);
        image.scale.setTo(.1);

But if I instead add the bitmap data directly to the canvas, the entire canvas is shown:


        var bmd = game.add.bitmapData(game.width, game.height);
        bmd.copy(game.canvas, 0, 0, game.width, game.height, 0, 0, null, null, 0, 0, 0);
        var image = game.add.image(200, 200, bmd);
        //      image.scale.setTo(.1);
       	var miniMap = bmd.addToWorld(200,200);


I wonder why converting it to an image cuts it off?

**Comment by photonstorm** [comment] 2015-05-19 14:07
Closing re: discussion on forum.

**Closed by photonstorm** 2015-05-19 14:07 UTC

**Comment by cscott5288** [comment] 2015-05-19 14:25
Link to the comment where this was answered:
http://www.html5gamedevs.com/topic/14598-canvastodataurl-only-takes-a-picture-of-visible-portion-or-is-phaser-cutting-it-off/?p=82967
