### ISSUE TITLE
PutTileAt function seem scale the sprite image to fit tile size

### ISSUE THREAD

**Issue by moJiXiang** [photonstorm/phaser#5647] opened 2021-04-06 08:34 UTC
## Version
* Phaser Version: Phaser 3.54.0
* Operating system: Windows
* Browser: Chrome

## Description
When use putTileAt function to draw a tile in an empty tile,  it seems scale the terrain sprite image to fit tile size.

Sprite image size is width: 64, height: 44, Tile size is width: 62, height: 31.

So, it seems scale image height from 44 to 31.

## Additional Information

![202146-163339](https://user-images.githubusercontent.com/5847011/113682576-e2228880-96f5-11eb-810e-e409ff5bd8df.png)

**Comment by moJiXiang** [comment] 2021-04-06 08:43
Same problem with #5644

**Comment by photonstorm** [comment] 2021-04-13 12:14
Duplicate of #5644 - please track in there. Also, there was no code sample provided, so we couldn't have used this issue anyway (please remember this in the future).

**Closed by photonstorm** 2021-04-13 12:14 UTC
Labels: 🗺️ Tilemap
