### ISSUE TITLE
Spine not showing after switching scenes

### ISSUE THREAD

**Issue by irenusfer** [photonstorm/phaser#4723] opened 2019-08-26 07:54 UTC
In my project i have a preloader scene and my main scene.
Im using the SpineBoy asset.

When i load and add it in the main scene without going through the preload scene - it is working fine.
When i load and add it in the main scene after i loaded other assets in the preload scene it is not showing.

console logs show it exists, it's parameters are fine, it is responding to events, but it is just not being displayed.

possibly a rendering issue?

**Comment by photonstorm** [comment] 2019-08-27 18:58
This is a duplicate of #4716 - so I'm going to close this issue. Please track resolution in there.

**Closed by photonstorm** 2019-08-27 18:58 UTC
