### ISSUE TITLE
Missing Typescript definition for Matter body

### ISSUE THREAD

**Issue by meisterpeeps** [photonstorm/phaser#4762] opened 2019-09-23 06:16 UTC
Using Phaser 3.19, I don't get any typescript information from an image for the body property.

`    const ship  = this.matter.add.image(100, 100, 'ship');
    this.ship = ship
    ship.setFrictionAir(.02);
    ship.setMass(30);
    ship.setFixedRotation();
    this.matter.world.setBounds(0, 0, 800, 300);
    ship.body`

ship.body has no properties from the matterjs api.   Looking into the dts for body 
`object | Phaser.Physics.Arcade.Body | Phaser.Physics.Impact.Body;`
It doesnt seem to include one for matter?

**Comment by photonstorm** [comment] 2019-11-19 13:09
Duplicate of #4694 - please track in there.

**Closed by photonstorm** 2019-11-19 13:09 UTC
