### ISSUE TITLE
PointerOver / PointerOut events only fire when clicking

### ISSUE THREAD

**Issue by iUltimateLP** [photonstorm/phaser#4604] opened 2019-06-20 10:51 UTC
## Version

* Phaser Version: 3.17.0

* Operating system: Win64

* Browser: Google Chrome

## Description

I am registering `pointerover` and `pointerout` events for a game object so I can create a hover effect, but it seems like these events are not firing when I hover over it. They only fire when I click and hold down the mouse button, but then, they also only fire once. Is this intended, or a I doing something wrong?

## Example Test Code

```js
        this.sprite = scene.add.image(this.x, this.y, this.template.id);

        // Register a handler for when the user clicks on this sprite
        this.sprite.on("pointerup", function() {
            this.template.onInteract(this);
        }, this);

        // Register a handler for when the users mouse hovers over the sprite
        this.sprite.on("pointerover", function() {
            console.log("hover");
        }, this);

        this.sprite.on("pointerout", function() {
            console.log("out");
        })

        // Enable interactivity so pointer events actually fire
        this.sprite.setInteractive();
```

**Comment by photonstorm** [comment] 2019-06-20 11:06
Please re-test with 3.18.1, as it contains multiple changes to the input system and addresses intermittent pointer events.

**Comment by iUltimateLP** [comment] 2019-06-20 12:06
Thanks for the quick reply. I updated, but unfortunately it didn't fix the issue :/

**Comment by iUltimateLP** [comment] 2019-06-20 12:38
Also, it seems like Phaser 3.18.1 sometimes forces the whole page to reload, is something like that known?

**Comment by photonstorm** [comment] 2019-06-20 14:27
There's nothing wrong with the code posted that I can see. Equally, these [Input examples](https://phaser.io/examples/v3/category/input/mouse) are working properly with 3.18, including this [over-out](https://phaser.io/examples/v3/view/input/mouse/over-and-out-events) one. So I don't believe this is an API issue at all, but rather one local to your setup / browser / implementation (outside of the code above).

The fact you're getting page reloading is very weird and I'd wager symptomatic of an underlying local problem.

**Comment by iUltimateLP** [comment] 2019-06-21 07:08
I'm having a HTML overlay over the whole game canvas for the game's UI, I'm not sure if that might affect it? How do you trace down the mouse events to game objects, is that done via window.onmousemove or any other events by chance?

**Comment by photonstorm** [comment] 2019-06-21 10:00
It's done by listening for mouse events on the game canvas, so if there is something over the top of the canvas that is intercepting these events, they will never reach the canvas.

**Comment by iUltimateLP** [comment] 2019-06-21 11:19
Yea, I might try disabling the pointer-events, all though I'm not sure if they propagate to all children. But thanks, I'll report back how it goes :)

**Comment by iUltimateLP** [comment] 2019-06-25 10:01
Hey, I tried disabling the pointer-events for the UI div container, but that didn't work. Is there any method I could still receive the hover events for my game objects? Remember, I do receive click events, just not hover events!

**Comment by sasstevens** [comment] 2019-08-19 20:31
Just to add, I'm also receiving this on Chrome. I've discovered that if I have dev tools open when I refresh the page I don't get any hover effects, but only click. However, if I close dev tools, refresh the page, then open dev tools, I get the console logs out.

**Comment by xense** [comment] 2019-08-22 07:35
I have the same problem, no `over `and `out `events are received from interactive object, like zone, if there is `div `over it. Even if the `div `is empty, but has obvious css size.

**Comment by scott20145** [comment] 2019-11-29 03:21
Same issue with version `3.0.19`.

**Comment by photonstorm** [comment] 2019-11-30 16:43
Thanks for posting your workaround @scott20145 - I'm going to close this issue off, as if you're overlaying any kind of html over the top of the Phaser canvas, it's your responsibility to ensure that they don't block input events from reaching the canvas, as Phaser cannot do this for you (as it has no knowledge of what else exists in the DOM, and nor should it be changing your page CSS rules, etc)

**Closed by photonstorm** 2019-11-30 16:43 UTC
Labels: 🙇‍♂️ User to test

**Comment by justincooper-415** [comment] 2020-12-18 17:08
I found on Mac, using Chrome 87.0.4280.88, the chrome developer console interfered with the pointerover events. So you might want to just turn off your dev console (if it's open) to see if its the source of your problem.

**Comment by Dercetech** [comment] 2021-05-03 14:23
Adding my 2 cents... hosting a Phaser instance in an Ionic app using Angular, be aware that Ionic/Angular (didn't try with React / Vue) will capture pointerover events and preventDefault() & co (no bubbling up, no trickle down).

In my case I have a global store that handles the switching between game states & the app to manage user profile & co. To allow capture pointerover events, I simple apply a global style to the angular app in its app.component.scss such as:

:host {
  display: none !important; /* otherwise the app interferes with touch events */
}

Restores the proper events channel to Phaser.

**Comment by Abhay-soni-developer** [comment] 2021-08-12 22:49
i think the problem is while you have opened your dev tools you have choose mobile view , and mobile does not have pointer thats why your pointer over and out works only on clicking. please close the dev tool or just change from mobile view to desktop and things will work out smooth for you
