### ISSUE TITLE
Phaser.Tilemaps.Tilemap#createBlankDynamicLayer does not accept key for tileset

### ISSUE THREAD

**Issue by jppresents** [photonstorm/phaser#4495] opened 2019-04-27 11:12 UTC
## Version

* Phaser Version: v3.16.2

* Operating system: Win10

* Browser: Chrome

## Description

The method  Phaser.Tilemaps.Tilemap#createBlankDynamicLayer has the following documentation (and therefore typescript datatypes) for tileset:

    * @param {(string|string[]|Phaser.Tilemaps.Tileset|Phaser.Tilemaps.Tileset[])} tileset - The tileset, or an array of tilesets, used to render this layer. Can be a string or a Tileset object.
  
But if a string identifing a tileset is passed, it does not work, only if the tileset object is passed.

## Example Test Code

working:

        let tileset = this.map.addTilesetImage("tileSet", "tiles", 16, 16, 0, 0);
        this.worldLayer = this.map.createBlankDynamicLayer("worldLayer", tileset);

not working:

        let tileset = this.map.addTilesetImage("tileSet", "tiles", 16, 16, 0, 0);
        this.worldLayer = this.map.createBlankDynamicLayer("worldLayer", "tileSet");

    
## Additional Information

Can be instantly recreated in this lab code:

http://labs.phaser.io/edit.html?src=src\game%20objects\tilemap\dynamic\base%20tile%20size.js

by providing a key for the tileset and then trying to use the key:

    // Load a 32 x 64 px tileset. This tileset was designed to allow tiles to overlap vertically, so
    // placing them on a 32 x 32 grid is exactly what we want.
    var tiles = map.addTilesetImage('walls_1x2', "tilesetkey", 32, 64);

    // Create a layer filled with random trees
    var layer = map.createBlankDynamicLayer('layer1', "tilesetkey");

The first line of code in the method already assumes that tileset is an object by accessing tileset.tileWidth

     if (tileWidth === undefined) { tileWidth = tileset.tileWidth; }

**Comment by Nallebeorn** [comment] 2019-05-23 12:14
Same two lines that cause troubles with an array of tilesets in #4294 and #4397

The documentation for createDynamicLayer() actually says that the default tileWidth and tileHeight will be the tilemap's values, not the tileset's. If the documentation is right here, this would be trivial to fix (just tileset.tileWidth -> this.tileWidth), but I'm not sure which way was intended?

**Comment by photonstorm** [comment] 2019-06-06 09:29
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed** 2019-06-06 09:29 UTC
