### ISSUE TITLE
Scenes are initialized too early when using `scene` property.

### ISSUE THREAD

**Issue by rblopes** [photonstorm/phaser#3185] opened 2018-01-24 14:21 UTC
Given the following code sample ([live](https://jsfiddle.net/rblopes/qevdd1yj/)):

```js
class SceneA extends Phaser.Scene {
  init() {
    //  NOTE: Should yield `SceneB { ... }`, etc.
    console.log(this.scene.get('SceneB'));
    console.log(this.scene.get('SceneC'));
  }

  create() {
    console.info('SceneA started.');
    this.scene
      .launch('SceneB')
      .launch('SceneC');
  }
}

class SceneB extends Phaser.Scene {
  create() {
    console.info('SceneB started.');
  }
}

class SceneC extends Phaser.Scene {
  create() {
    console.info('SceneC started.');
  }
}

const 
  scenes = [SceneA, SceneB, SceneC],
  game = new Phaser.Game({
    type: Phaser.AUTO,
    width: 320,
    height: 240,
    
    scene: scenes.map(S => new S({key: S.name})),
    
    //  NOTE: Alternatively, add scenes after the game is booted.
    /*
    callbacks: {
      postBoot() {
        for (let S of scenes) {
          game.scene.add(S.name, S);
        }
    
        game.scene.start('SceneA');
      }
    }
    */
  });
```

When using the `scene` property of `Phaser.Game` configuration object, scenes are initialized as soon as they are consumed by `SceneManager`. I'm not sure this is the desired behavior there. In the example above, querying `SceneB` returns `null`, but that scene can be started with no problems later, because how the scene manager schedules that scene to be run in a next cycle, which, in this case, is a bit surprising, in my opinion.

Otherwise, if I delay initialization of scenes as a workaround ─ the last commented block of code is one example ─, querying the scene yields the desired result.

**Comment by rblopes** [comment] 2018-01-25 15:48
I've found out that declaring a payload in the first scene delays its initialization too, giving time for the second one to be added to the scene manager.

<details>
<summary>Sample code</summary>

```js
const sceneA = {
    key: 'SceneA',
    
    files: [{
        key: 'aqua_ball',
        type: 'image',
        url: 'assets/sprites/aqua_ball.png'
    }],

    create() {
        //  NOTE: Should yield `Scene { ... }`.
        console.log(this.scene.get('SceneB'));

        this.scene.launch('SceneB');

        console.info('SceneA started.');
    }
};

const sceneB = {
    key: 'SceneB',
    
    create() {
        console.info('SceneB started.');
    }
};

const game = new Phaser.Game({
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',

    scene: [sceneA, sceneB]

    //  NOTE: Alternatively, add scenes after the game is booted.
    // callbacks: {
    //     postBoot() {
    //         for (let S of [sceneA, sceneB]) {
    //             game.scene.add(S.key, S);
    //         }
    //         game.scene.start('SceneA');
    //     }
    // }
});
```

</details>

**Comment by rblopes** [comment] 2018-03-05 15:36
While testing the changes made after 7c16368d3e46467b95faec594b54e197d1827cf8, I've found one problem adding scenes defined as objects rather than classes.

The second code sample posted defines three scenes as plain objects. I made that to be sure the problem could be reproduced the same way.

Testing against the current master branch, using ES6 classes works as expected. But when using plain objects, the scene manager traverses the queue in reverse order (had not the time to check the implementation code), but stops when it encounters the first object and initializes that scene, even if the last one is a class.

<details>
<summary>Sample 1 (working)</summary>

```js
class SceneA extends Phaser.Scene {
    constructor() {
        super({key: 'SceneA'/*, files: [{
            key: 'aqua_ball',
            type: 'image',
            url: 'assets/sprites/aqua_ball.png'
        }]*/});
    }

    preload() {
        this.load.image('aqua_ball', 'assets/sprites/aqua_ball.png');
    }

    create() {
        console.info('SceneA started.');
        this.scene
            .launch('SceneB')
            .launch('SceneC');
    }
}

class SceneB extends Phaser.Scene {
    constructor() {
        super('SceneB');
    }

    init() {
        setTimeout(
            () => {
                console.log(this.scene.get('SceneA'));
                console.log(this.scene.get('SceneB'));
                console.log(this.scene.get('SceneC'));
            },
            1000
        );
    }

    create() {
        console.info('SceneB started.');
    }
}

class SceneC extends Phaser.Scene {
    constructor() {
        super('SceneC');
    }

    create() {
        this.add.image(160, 120, 'aqua_ball')
        console.info('SceneC started.');
    }
}

const game = new Phaser.Game({
    type: Phaser.AUTO,
    width: 320,
    height: 240,
    scene: [SceneA, SceneB, SceneC]
});
```
</details>

<details>
<summary>Sample 2 (not working)</summary>

```js
const SceneA = {
    key: 'SceneA',

    // files: [{
    //     key: 'aqua_ball',
    //     type: 'image',
    //     url: 'assets/sprites/aqua_ball.png'
    // }],

    preload() {
        this.load.image('aqua_ball', 'assets/sprites/aqua_ball.png');
    },

    init() {
        //  NOTE: Should yield `SceneB { ... }`, etc.
        console.log(this.scene.get('SceneB'));
        console.log(this.scene.get('SceneC'));
    },

    create() {
        console.info('SceneA started.');
        this.scene
            .launch('SceneB')
            .launch('SceneC');
    }
};

const SceneB = {
    key: 'SceneB',

    init() {
        setTimeout(
            () => {
                console.log(this.scene.get('SceneA'));
                console.log(this.scene.get('SceneB'));
                console.log(this.scene.get('SceneC'));
            },
            1000
        );
    },

    create() {
        console.info('SceneB started.');
    }
};

class SceneC extends Phaser.Scene {
    constructor() {
        super('SceneC');
    }

    create() {
        this.add.image(160, 120, 'aqua_ball')
        console.info('SceneC started.');
    }
}

const game = new Phaser.Game({
    type: Phaser.AUTO,
    width: 320,
    height: 240,
    scene: [SceneA, SceneB, SceneC]
});
```
</details>

**Comment by photonstorm** [comment] 2018-03-05 17:00
Boot scenes are always iterated first to last, never in reverse. They're only iterated in reverse during the game step, which hasn't happened yet during boot.

The issue was that the bootQueue method was replacing the Object key property (because that is what the `add` method does and it was copied from there) but it didn't ought to. Have removed that and it now runs as expected.

**Comment by rblopes** [comment] 2018-03-05 17:17
> Boot scenes are always iterated first to last, never in reverse.

Good point. Like I said before, had not the time to look into the implementation at that time. In one of the tests I did with three scene objects, only the last one got started, that led me to think the queue was traversed backwards.

Did some quick tests again to confirm, the samples are working as expected.

**Comment by pixelhijack** [comment] 2018-03-10 07:48
Might be a similar rooted issue or slightly related, if so, i should have open a new issue, following the Scene Manager documentation https://phaser.io/phaser3/api/scene-manager

**Setup**

`const bootScene = {
    key: 'boot',
    active: true,
    init: (config) => {
        console.log('[BOOT] init', config);
    },
    preload: () => {
        console.log('[BOOT] preload');
    },
    create: (config) => {
        console.log('[BOOT] create', config);
    },
    update: () => {
        console.log('[BOOT] update');
    }
};

const gameScene = {
    key: 'game',
    active: true,
    renderToTexture: true,
    x: 64,
    y: 64,
    width: 320,
    height: 200,
    init: (config) => {
        console.log('[GAME] init', config);
    },
    preload: () => {
        console.log('[GAME] preload');
    },
    create: (config) => {
        console.log('[GAME] create', config);
    },
    update: () => {
        console.log('[GAME] update');
    }
};

const gameConfig = {
    type: Phaser.CANVAS,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: [ bootScene, gameScene ]
};

const game = new Phaser.Game(gameConfig);
game.scene.start('boot', { someData: '...arbitrary data' });
 `

**Expected behaviour**
Based on Phaser 2.x States, what i want to achieve and expect is 

1. I have two scenes, both with unique keys i give ("boot", "game") their corresponding config data (JSON level, game config etc) which i want to pass down
2. In Phaser 2.x and supposedly in Phaser 3 this data is passed to the state/scene .init() and .create() methods 
3. I can initialise first Boot scene, from where (if any key hit etc) i can start the Game scene

**Actual behaviour**

1. Scenes are initialised with the "default" fallback key
2. My data is never passed down, only a default { } empty object i got
3. Scenes are starting at the same time, their update() methods are called at the same time 

![screen shot 2018-03-09 at 13 25 40](https://user-images.githubusercontent.com/5672651/37239617-802ae8c4-243f-11e8-954a-1b879fa67246.png)

**Cause?**
`for (var i = 0; i < this._pending.length; i++)
            {
                var entry = this._pending[i];

                if (entry.key === key)
                {
                    entry.autoStart = true;
                    entry.data = data;
                }
            }`

At Phaser 3.2.0. SceneManager.js:947 if i debug i see that the entry.key is always the "default", not my keys ("boot", "game"), therefore the default entry.data = {} is passed. 

As pointed out in the forums, setting the 'active' property can cause this, but if i set the active to false, i got the same results. http://www.html5gamedevs.com/topic/36148-phaser-3-scene-phaser-2-state-passing-data-to-init-when-start/

**Issue?**
Can you please approve this is an expected behaviour OR a bug?
If expected, how can I replicate the Phaser 2 State flow (initialize one state at a time, pass data, start another state, only one state is running) in Phaser 3?

**Comment by photonstorm** [comment] 2018-03-10 10:01
This isn’t related, please copy pasta to a new issue with ‘scene data’ somewhere in the title.

**Comment by pixelhijack** [comment] 2018-03-10 10:10
thanks @photonstorm , done! https://github.com/photonstorm/phaser/issues/3363

**Comment by photonstorm** [comment] 2018-04-09 13:12
Going to close this issue off, as the original problem is now resolved and the additional one is too! :)

**Closed by photonstorm** 2018-04-09 13:12 UTC
Labels: needs checking
