### ISSUE TITLE
Frequently getting WebGL error in Firefox with Phaser 2.4.8, parts of game don't show

### ISSUE THREAD

**Issue by byondrealdev** [photonstorm/phaser#2534] opened 2016-06-05 07:16 UTC
(Hi @photonstorm, great fan of your framework here, can't wait for Lazer!)

This Issue is about:
- A bug in the API

Getting the following error only in Firefox, only since 2.4.8:

```
Error: WebGL: texImage2D: Failed to get data from DOM element. Implicit width and height for this upload will be zero. phaser.js:7:27510
Error: WebGL: drawElements: Active texture 0 for target 0x0de1 is 'incomplete', and will be rendered as RGBA(0,0,0,1), as per the GLES 2.0.24 $3.8.2: The dimensions of `level_base` are not all positive. phaser.js:8:9503
```

Happens frequently, but not always.
Switching Phaser version to 2.4.7 fixes the issue.

Game is using textures of maximum size 4096x4096.

Would be difficult for me to create a simplified sample with reproducible bug, but I can try if you need it.
Any help would be great, this is for a product shipping in a matter of days, and we really want to use 2.4.8 .

**Comment by byondrealdev** [comment] 2016-06-05 07:46
On mapping the line number and character position above with unminified phaser.js, these are the lines which trigger the WebGL errors:

        gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, texture.source);

and

        gl.drawElements(gl.TRIANGLES, size * 6, gl.UNSIGNED_SHORT, startIndex * 6 * 2);

**Comment by photonstorm** [comment] 2016-06-05 15:03
The error is basically saying "I can no longer read this Image". Either it hasn't finished loading, or has been erased from memory for some reason. Are you doing anything complex with regard to image management? Constant clearance of textures for example, or on the fly image loading?

**Comment by byondrealdev** [comment] 2016-06-05 22:04
No, game has 5 large spritesheets (4096x4096) that all load using plane old `game.load.atlas` in `game.state.preload`, moving to play state using regular `game.state.create`.
I checked network requests as well, all were 200 or 304.
Anything special that 2.4.8 might be doing in this regard?

**Comment by byondrealdev** [comment] 2016-06-05 22:07
Not clearing any textures manually.
Also, using `this.load.crossOrigin = 'anonymous'` for loading atlas images from a cdn url

**Comment by photonstorm** [comment] 2016-06-05 22:07
Nope, nothing has changed in 2.4.8 with regard to asset loading or the WebGL renderer at all.

That doesn't mean Firefox hasn't changed though.

**Comment by byondrealdev** [comment] 2016-06-05 22:22
That's weird, problem seems to go away if I switch back to 2.4.7, keeping the same firefox..

Just to give you more information, this is how the code is structured:

`LoadScreen` (extends Phaser.State)

  - preload - just calls `this.load.atlas` for 6 sprites, and `this.load.audiosprite` for 2 audio sprites.
  - create - calls `this.state.start('PLAY')` to navigate to `PlayScreen`

`PlayScreen` (extends Phaser.State)

  - create - calls `game.add.group`, `game.add.sprite` etc to create game objects

**Comment by photonstorm** [comment] 2016-06-05 22:27
Look at the 2.4.8 change log for yourself: https://github.com/photonstorm/phaser#change-log there's literally nothing Loader / Renderer related in it (except some sprite tint fixes).

Try it with 2.4.9 instead and see what happens. Failing that, if 2.4.7 works, stick with it.

**Comment by hilts-vaughan** [comment] 2016-06-06 01:29
You can also try a git bisect to try and isolate it. :)

**Comment by fzuleta** [comment] 2016-06-16 06:06
hi, this is happening to me as well, really need to fix this, 

for me it's happening in Firefox windows and mac, phaser 2.4.7 (cant use 2.4.8 due to a button isOver bug), and both refreshing or loading the same window or a new window. 
if I wait a bit after I close the site and try again in a new window, the page works. very strange

would this be a phaser issue or FF issue?
 
![phaser-error](https://cloud.githubusercontent.com/assets/3056157/16106860/9c1c14fa-33db-11e6-80a7-f0f27b401ca4.png)

**Comment by photonstorm** [comment] 2016-06-20 12:59
Given it doesn't happen in any other browser, it's clearly a FF specific issue. However that doesn't mean we can't fix it, but unless someone can help isolate what causes it, this one is likely to remain unsolved for a while.

**Comment by photonstorm** [comment] 2016-06-20 13:05
This is going to be related to one of the following:

1) The Loader events. Maybe something changed in the way FireFox deals with load / ready events from Image tags, and the image isn't actually fully ready for use, even though the event said otherwise (so Phaser carried on).

2) Uploading large textures to WebGL is taking too long on specific FF / GPU combos, and Phaser is trying to use them before they're actually ready for rendering. Maybe there is a new event to listen for? Although I'm positive it has always been a synchronous process in the past, and not event driven.

**Comment by Downi** [comment] 2016-08-31 16:02
Ohai,

sorry for digging out this kind of old issues, but this still somehow persists in the latest 2.6.2 version. It first appeared after a driver update of an R7 250 GPU in combination with win7 x86 and mac os (version unknown atm).

Is there any solution to this yet? :s

**Comment by photonstorm** [comment] 2016-08-31 17:31
This still needs a working test case to isolate it, before any further action can happen.

**Comment by photonstorm** [comment] 2016-09-26 21:09
Anyone willing to see if this is still the case with the Phaser 3 build in the dev branch please? (if not, I'll close this one off, as I can't reproduce, so it's like shooting in the dark)

**Comment by Downi** [comment] 2016-09-27 03:35
Will do.
Sadly I were unable to provide an example - seemed just to happen with the game we are doing at work :S

**Comment by Downi** [comment] 2016-09-27 08:17
Yeah, it does still happen. Not as often as with the latest 2.x release, but it does still happen. /=

**Comment by vpmedia** [comment] 2017-01-18 09:26
I think the issue is very similar what has been described here:
http://www.html5gamedevs.com/topic/17328-phaser-bug-when-reloading-page-with-f5/
I also noticed this using Phaser v2.6.2 or v2.6.3-CE and Firefox (desktop) v48-50.
And the provided workaround to comment out a few lines in Loader.loadImageTag mitigated it (do not reload file from cache(?)).

**Comment by vpmedia** [comment] 2017-01-18 11:00
Maybe its worth to add that I've encountered the problem only when using texture atlases but not with separated images.

**Comment by photonstorm** [comment] 2017-01-18 11:20
You're welcome to issue a pull request against the Phaser CE version with that change in.

**Comment by vpmedia** [comment] 2017-01-18 12:18
Here we go:
https://github.com/photonstorm/phaser-ce/pull/3

**Closed** 2017-01-18 12:23 UTC
Labels: bug (browser), code example needed

**Comment by MDBrittingham** [comment] 2019-10-11 17:42
Hi folks - here is how this shook out for me.  First, I am not using Phaser at this point (just PIXI JS) but PhotoStorm's comment about WebGL trying to use images before they were quite ready (and the fact that we are all on WebGL) got me thinking that my animation loop might be starting up before all of my sprites were loaded up.  So I put a very slight delay on the animation loop startup and the problem went away.  This is only on FireFox but it seems to be a permanent fix.
