### ISSUE TITLE
RenderTexture Memory Leak

### ISSUE THREAD

**Issue by sjb933** [photonstorm/phaser#4239] opened 2018-12-16 07:09 UTC
## Version

* Phaser Version: 3.15.1

* Operating system: Windows 10, Mac OS

* Browser: Verified issue on Chrome and Firefox, no other browsers tested

## Description

Using **`RenderTexture`** exposes a memory leak, presumably in the **`TextureManager`**.

## Example Test Code
I'm working in a more complex typescript/webpack build setup, but I've created a reduced example for reproducing the issue:

1. Load the test in browser, take a memory snapshot.
2. Press `SPACE` to recreate the scene, take another snapshot and compare.

```html
<!DOCTYPE html>
<html>

<head>
  <script src="https://cdn.jsdelivr.net/npm/phaser@3.15.1/dist/phaser-arcade-physics.min.js"></script>
</head>

<body>

  <script>
    var MyScene = new Phaser.Class({

      Extends: Phaser.Scene,

      initialize: function MyScene(config) {
        Phaser.Scene.call(this, { ...config, key: 'MEMLEAK' })
      },

      create: function () {
        console.log("CREATE SCENE");

        // instantiation of this object creates a leak
        const rTex = this.add.renderTexture(200, 150, 400, 300).fill(0x990000);

        /** 
        * you can manually destroy this texture here and the leak is still present
        * this makes no real difference as the texture is destroyed when the scene is restarted
        */
        // rtex.destroy();

        // PRESS SPACEBAR TO RECREATE THE SCENE AND CAUSE THE LEAK - COMPARE MEMORY SNAPSHOTS TO OBSERVE BEFORE/AFTER
        this.input.keyboard.removeAllListeners();
        this.input.keyboard.on('keydown_SPACE', () => game.scene.start('MEMLEAK'));
      }

    });

    const config = {
      type: Phaser.WEBGL,
      width: 800,
      height: 600,
      input: {
        keyboard: true
      },
      backgroundColor: '#000000',
      scene: MyScene
    };

    const game = new Phaser.Game(config);

  </script>

</body>

</html>
```

## Additional Information
Screenshots from Chrome and Firefox memory comparisons:

**Chrome**
![image](https://user-images.githubusercontent.com/3180446/50050995-bd421b80-00ce-11e9-874f-365fe9f5e43b.png)

**Firefox**
![image](https://user-images.githubusercontent.com/3180446/50050988-7d7b3400-00ce-11e9-9e25-809951367542.png)

**Comment by sjb933** [comment] 2018-12-16 07:17
I verified that this issue occurs in both **`CANVAS`** and **`WEBGL`** mode.  Let me know if I can provide any additional information.  I appreciate all the time and effort put into this project 🍻

**Comment by photonstorm** [comment] 2018-12-18 15:21
The issue is that you're not using the Scene Plugin to change the Scene, but are going directly via the Scene Manager. This means the
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by photonstorm** [comment] 2018-12-18 15:22
Also, although it doesn't make any difference this time, please use the Scene Plugin, not the Scene Manager (`game.scene`) as it won't have a chance to run any other events in the current queue.

**Closed by photonstorm** 2018-12-18 15:21 UTC

**Comment by sjb933** [comment] 2018-12-19 18:39
Awesome, thank you for the quick support!  🍻
