### ISSUE TITLE
Stroke width not correct

### ISSUE THREAD

**Issue by nickaversano** [photonstorm/phaser#3478] opened 2018-03-30 16:24 UTC
I've noticed that with the following code, the stroke width is actually two (2) pixels instead of one (1) and is a little fuzzy instead of being sharp:

```javascript
var g
function create() {
  g = this.add.graphics()
}

function update() {
  g.clear()
  g.lineStyle(1, 0x00ff00, 1)
  g.strokeRect(8, 8, 32, 32)
}
```

Produces:
![stroke-rect](https://user-images.githubusercontent.com/5448363/38145125-cdb70bd2-3415-11e8-8d9d-bddd34a6f06d.png)

This happens when drawing paths or rectangles. It seems like the path is actually being drawn in between two pixels.

Interestingly enough, if I adjust the stroke numbers to be `g.strokeRect(8.5, 8.5, 32, 32)` I get a crisp rectangle:
![screen shot 2018-03-30 at 12 31 48 pm](https://user-images.githubusercontent.com/5448363/38145278-88776ea8-3416-11e8-906e-0930cce79e4d.png)

It's also worth noting that this rectangle is actually 33px x 33px. `g.strokeRect(8.5, 8.5, 31, 31)` will produce a 32x32 rectangle starting at position (8, 8).

**Comment by wtravO** [comment] 2018-03-30 20:22
This is actually not a Phaser bug and is a bug with Chrome's canvas rendering it seems.

I was able to replicate the bug in Chrome, however, it worked as intended in all other browsers that I tested. (IE, Firefox, Edge)

**Comment by nickaversano** [comment] 2018-03-30 23:44
@wtravO code to repro?

**Comment by wtravO** [comment] 2018-03-31 01:47
https://github.com/photonstorm/phaser3-examples/blob/master/public/src/game%20objects/graphics/graphics%20styles.js

**Comment by wtravO** [comment] 2018-03-31 02:08
I have created an issue for it over at Chromium.
https://bugs.chromium.org/p/chromium/issues/detail?id=827751

Please Star it in order for it to get quickly resolved. :)

**Comment by nickaversano** [comment] 2018-03-31 02:41
Awesome, thanks!

**Comment by photonstorm** [comment] 2018-04-03 16:33
Have starred the issue too and will track it. Am going to close this issue off as there's nothing we can really do about it, sorry. Fingers crossed for Google.

**Closed by photonstorm** 2018-04-03 16:33 UTC
