### ISSUE TITLE
phaser3 the API this.load.image() don't support the base64 type

### ISSUE THREAD

**Issue by tyust512** [photonstorm/phaser#5080] opened 2020-04-06 10:26 UTC
# Version
Phaser 3
## Description
when i use the vue-cli with "@vue/cli-service": "~4.2.0", the webpack url-loader will change small images into base64, but the phaser 3 isn't supported it, the phaser's canvas area becomes blank color with no error or warn in the chrome console

## Example Test Code
	import Phaser from 'phaser'
	import background from '@/assets/images/background.png'
	import player from '@/assets/images/player.png'
	
	const config = {
	  type: Phaser.AUTO,
	  width: 200,
	  height: 200,
	  parent: '',
	  dom: {
	    // createContainer: true,
	  },
	  physics: {
	    default: 'arcade',
	    arcade: {
	      // gravity: { y: 200 },
	      debug: false,
	    },
	  },
	  scene: { // 场景
	    preload: preload, // () => alert('abc')
	    create: create, //
	    // update: _update,
	    // render: _render,
	  },
	}
	
	function preload () {
	  this.load.image('background', background)
	  this.load.image('player', player)
	  // this.load.baseURL = ''
	  // this.load.crossOrign = ''
	}

## Additional Information
when i only use the background image, it is good because it is a big image, the url-loader don't change it it to base64, but the player image is a small image. I alert it, it becomes the base64.
There is no error or warning in the Chrome console log, if i comment `this.load.image('player', player)`, the phaser will be ok again.

Please tell me the solution, if there is no idear, i only can change the `vue.config.js` `url-loader` options.

thanks

**Comment by Alexemarg** [comment] 2020-04-06 21:35
#3897

**Comment by hexus** [comment] 2020-04-07 00:24
Thanks for the link Alexemarg. Closing this because it's a duplicate of #3897.

**Closed by hexus** 2020-04-07 00:24 UTC
Labels: 👎Won't Fix

**Comment by tyust512** [comment] 2020-04-07 01:11
thanks.
