### ISSUE TITLE
stickey keys

### ISSUE THREAD

**Issue by BinaryMoon** [photonstorm/phaser#1485] opened 2014-12-24 11:00 UTC
I noticed when playing with the keyboard controlled demos that the keys are sticking. I've tried quite a few of the demos on the examples site and can reproduce this every time.

The issue is that the key sticks down after being pressed, if you press more than one key at a time.

For example in the starstruck demo (http://examples.phaser.io/_site/view_full.html?d=games&f=starstruck.js&t=starstruck) if you press and hold the right key to run right, and then press and release the spacebar to jump (keep right arrow pressed), then you can let go of the right arrow and the character will keep running right until the right arrow is pressed and released once more.

**Comment by fillmoreb** [comment] 2015-01-14 22:32
I just tested this on OSX 10.10.1, on a Macbook Pro, using Google Chrome 39.0.2171.99.  Was not able to reproduce the sticky keys.

**Comment by nesukun** [comment] 2015-01-22 14:05
Chrome 41 is not yet stable channel AFAIK, try first in an incognito window (which disables all extensions unless told otherwise) and if the problem persists, probably is a beta bug.

**Comment by photonstorm** [comment] 2015-02-10 21:43
Going to close this one off I'm afraid, as I just re-tested Chrome on OS X with no ill effects, so am thinking it's Canary / device specific.

**Closed by photonstorm** 2015-02-10 21:43 UTC
