### ISSUE TITLE
Image.on('pointerdown') not firing

### ISSUE THREAD

**Issue by sekaru** [photonstorm/phaser#4321] opened 2019-01-26 13:59 UTC
## Version

* Phaser Version: 3.16 (RC-1)

* Operating system: MacOS

* Browser: Safari/Chrome

## Description

Image pointer down events don't seem to be firing.

## Example Test Code
`    let speaker = this.add.image(0, 0, 'speaker_off').setInteractive();`

  `  speaker.on('pointerdown', (pointer, x, y, event) => console.log('hi'));`

## Additional Information
The image is within a container but it doesn't seem to work if its in or out of the container. The scene is also rendered on top of another scene.
Seems as if it fires on larger images but smaller images (say 32x32 sprites) don't have the event firing.

**Comment by photonstorm** [comment] 2019-01-26 18:00
Do you have a full test case please? Because the event fires fine on Safari for me, no matter the image size. Possibly making the cause the scene stacking.

**Comment by sekaru** [comment] 2019-01-26 18:44
`create() {
    this.phone = this.add.image(0, 0, 'phone');

    let speaker = this.add.image(0, 0, 'speaker_off').setInteractive();

    const phoneHiddenY = this.sys.game.canvas.height + this.phone.height;
    const phoneActiveY = this.sys.game.canvas.height - this.phone.height / 2 - 10;
    this.phoneContainer = this.add.container(this.phone.width / 2 + 10, phoneHiddenY);

    this.phoneContainer.add([
      this.phone,
      speaker
    ]);

    speaker.on('pointerdown', (pointer, x, y, event) => {
      this.speakerOn = !this.speakerOn;
      speaker.setTexture(this.speakerOn ? 'speaker_on': 'speaker_off')
    });
  }`

I've attached the graphics too. Cheers.
[graphics.zip](https://github.com/photonstorm/phaser/files/2799370/graphics.zip)

**Comment by sekaru** [comment] 2019-01-26 21:34
Also it works in 3.15 down

**Comment by photonstorm** [comment] 2019-01-28 22:50
Still stuggling to replicate this. I've made the following test case, which uses parallel Scenes running and I can click all 3 images just fine in Safari, Chrome, etc: http://labs.phaser.io/view.html?src=src/bugs/click%20scenes.js&v=dev

I'll try a test using your exact code and assets, but I'm wondering if the above works when you test it?

**Comment by photonstorm** [comment] 2019-01-29 01:06
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed by photonstorm** 2019-01-29 01:06 UTC
Labels: 🐛 Bug (beta), 🔥 Priority: Urgent

**Comment by TheJasonReynolds** [comment] 2019-01-29 04:00
I ran into a very similar issue trying the RC-1, however it seems to be the scale manager and pointer coordinates. Previously I used CSS to resize the game, I tried to set scale:{mode:Phaser.DOM.NONE} but still was unable to get events on a sprite when the canvas scale has been changed with CSS. Any suggestions/other ways to turn scale manager off?

**Comment by photonstorm** [comment] 2019-01-29 08:32
That isn’t the same issue @TheJasonReynolds please open on its own
