### ISSUE TITLE
Setting position of nested containers results in combined dimensions instead of position change

### ISSUE THREAD

**Issue by GaryStanton** [photonstorm/phaser#4644] opened 2019-07-09 23:18 UTC
## Version
* Phaser Version: 3.18.1

## Description
When adding an object to a container, its dimensions grow to fit the object. Setting the position of the container moves it around. This is as I'd expect.
However, if the container contains a _child_ container, it seems that instead of _moving_, the parent container _grows_ to incorporate the new position. 

e.g. If you create a container at 0,0 and add a sprite (say, 50 x 50px) to it, its bounds change to incorporate the sprite. Then if you move the container (with `setX(100)` for instance) then the bounds change to show the new position. ( `x:100, y:0, width:50, height:50` ) 

If you do this with a nested container, (add a sprite to child container, add container to the parent container, then call `setX(100)` on the parent) instead of the position changing it simply adds to the dimensions of the container - so you end up with `x:0, y:0, width:150, height:50` .

## Example Test Code

I have a pen here: https://codepen.io/garystanton/pen/KjrmMe
Check the console to see that the `getBounds()` call on the parent container has a position of 0,0 instead of being moved with the `setX()` call.

**Comment by photonstorm** [comment] 2019-07-15 09:36
Pretty sure this is a duplicate of #4580

**Comment by photonstorm** [comment] 2022-11-17 15:29
Closing as this was fixed in the v3.23.0 release (and remains fixed in 3.60)

**Closed by photonstorm** 2022-11-17 15:29 UTC
Labels: 📦 Container
