### ISSUE TITLE
Phaser.Text's wordwrap doesn't work with Chinese words

### ISSUE THREAD

**Issue by chaping** [photonstorm/phaser#1986] opened 2015-08-06 17:06 UTC
There are no spaces between Chinese words,but Phaser splits words by space,so the `wordWrap` and `wordWrapWidth` property have no effect on Chinese.

**Comment by photonstorm** [comment] 2015-08-06 21:02
Yes sorry about this, I'm not sure of the best way to address it though. How should it wrap words without spaces? I can't pick a number of characters, because that could chop a word entirely in two - what should be done?

**Comment by the-simian** [comment] 2015-08-24 12:03
I saw this thread while browsing, and I realized I didn't know the answer either. I found this interesting resource though, and i'd like to share : [https://msdn.microsoft.com/en-us/goglobal/bb688158.aspx](https://msdn.microsoft.com/en-us/goglobal/bb688158.aspx)

**Comment by photonstorm** [comment] 2016-02-04 15:23
Closing as it's a duplicate of #1403

**Closed by photonstorm** 2016-02-04 15:23 UTC
Labels: feature request
