### ISSUE TITLE
getTileCollisionGroup receiving Tileset array instead of expected single reference

### ISSUE THREAD

**Issue by Phillor** [photonstorm/phaser#4107] opened 2018-10-10 18:25 UTC
## Version

* Phaser Version: 3.14.0

* Operating system: Windows 10

## Description

When the scene.matter.world.convertTilemapLayer(Layer) function is called, while tiles in the stated Layer having a collision set, the following error will be printed in the console:
TypeError: this.tileset.getTileCollisionGroup is not a function

This is because getTileCollisionGroup expects a single reference to the Tileset while getting an array of Tileset objects since Phaser Version 3.14.0.

In Phaser 3.13.0 scene.matter.world.convertTilemapLayer(Layer) works fine.

## Example Test Code

```
let gameScene = new Phaser.Scene('Game');


gameScene.preload = function() {
	this.load.image('tileset', 'assets/tileset.png');
	this.load.tilemapTiledJSON('map', 'assets/tilemap.json');
};

gameScene.create = function() {
	
	var map = this.make.tilemap({ key: 'map' });

	var tileset = map.addTilesetImage('tileset');

	var layer = map.createDynamicLayer("layer1", tileset, 0, 0);
	
	layer.setCollisionByProperty({ collides: true });

	this.matter.world.convertTilemapLayer(layer);
	
};

gameScene.update = function() {
	}

};

let config = {
	width: 700,
	height: 500,
	type: Phaser.AUTO,
	scene: gameScene,
	backgroundColor: 0x4583ff,
	physics: {
		default: 'matter',
		matter: {
			gravity: {x: 0, y: 0},
			debug: true
		}
	}
};

let game = new Phaser.Game(config);
```

## Additional Information

The function getCollisionGroup should be modified, giving the array element of the right Tileset to getTileCollisionGroup.

**Comment by photonstorm** [comment] 2018-10-12 18:06
This is a duplicate of #4095 so please track progress on this issue in there.

**Closed by photonstorm** 2018-10-12 18:06 UTC
