### ISSUE TITLE
x, y coordinate shifted when you have html before the <div id="phaser"></> 

### ISSUE THREAD

**Issue by fromnowhereuser** [photonstorm/phaser#4678] opened 2019-07-26 06:59 UTC
When Phaser took the entire place of the page, there is no probleme using the pointer or touch event.

But when i have some html before <div #phaserview></div> (i use angular)

all y coordinates are shifted. The shift seems to be the same size of the HTML placed before.

Do you have any solutions to dynamically set y shift to correct that ?

Thx you again

**Comment by fromnowhereuser** [comment] 2019-07-26 07:56
Actually, i have news:
when i track 
  update(time): void {
    console.log(this.input.x);
    console.log(this.input.y);

I have at 0,0 the value (0, -40). I REALLY dont know where this can come from...
If you have any advise...

**Comment by photonstorm** [comment] 2019-07-26 11:07
There's no setting to 'shift' the coordinates because Phaser doesn't need one, it doesn't care where on the page the canvas is, it'll translate the input coordinates, regardless what comes before it in the HTML.

`input.x` and `y` shouldn't really be used, for the reasons given in the docs. You should listen for input events such as `this.input.on('pointermove', (pointer) => { consoole.log(pointer.x) }`

I'm going to close this off, as this isn't a demonstrable bug in the API, has no reproducible code sample and feels more like something that should be resolved via support channels like the Phaser Forum or Discord. If you can post code demonstrating an issue then I'll be happy to look into it, otherwise I look forward to seeing you on the forum / in chat.

**Closed by photonstorm** 2019-07-26 11:07 UTC
