### ISSUE TITLE
TileSprite on Canvas mode does not render correctly

### ISSUE THREAD

**Issue by jmp909** [photonstorm/phaser#2164] opened 2015-10-26 01:05 UTC
This example works fine in WEBGL mode but is broken under CANVAS
http://jsfiddle.net/jLgsrpfp/2/

I can't work out what the shift relates to either. Taking the angle off the Sprite doesn't fix it

![webgl bug](http://www.html5gamedevs.com/uploads/monthly_10_2015/post-16536-0-90103100-1445820342.jpeg)

**Comment by photonstorm** [comment] 2015-10-26 19:31
Are you sure this is a TileSprite issue and not a Graphics mask one? because I'd put money it it being mask related.

**Comment by jmp909** [comment] 2015-10-26 19:44
it works fine with BitmapData and a mask
http://jsfiddle.net/znw7awmr/2/

hence why i've raised it as a TileSprite issue, but could be a combination of Mask + TileSprite i guess.

**Comment by jmp909** [comment] 2015-10-26 20:02
i've found the issue here but I can't explain it specifically... seems to be a problem with tileScale.
http://jsfiddle.net/1d6prbc7/1/

if you change my useScaledBitmap variable to true it fixes it so the bug is occurring in the code below when using tileScale.. the "registration point" seems to be getting shifted

```javascript
earth=game.add.tileSprite(0,0,250,250,'texture')
// scale the 1280x512 map to fit in a 250 height...
var scale=size/mapH   // 250/512
earth.tileScale = new Phaser.Point(scale, scale)
```

**Comment by jmp909** [comment] 2015-10-26 20:10
yes just checked.. try changing scale to 0.1... the top left of the TileSprite shifts further down/right on the screen, the smaller the scale is. (and vice versa shifts up/left-wards the higher the tileScale)

**Comment by jmp909** [comment] 2015-10-26 20:18
oh...

"The anchor sets the origin point of the texture"

i had assumed it set the origin of the tilesprite, not the texture that it displays:S

although that seems like unexpected behaviour, as the texture is essentially then offsetting the sprite as per my example above?

**Comment by photonstorm** [comment] 2016-02-18 14:01
Confirmed Pixi bug. No obvious fix yet.

**Comment by photonstorm** [comment] 2017-04-20 12:32
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.

**Closed by photonstorm** 2017-04-20 12:32 UTC
Labels: bug (pixi)
