### ISSUE TITLE
Sprite animation inside SpriteBatch

### ISSUE THREAD

**Issue by qdrj** [photonstorm/phaser#1951] opened 2015-07-29 09:14 UTC
Animations inside SpriteBatch are not working since 2.3.0 release. I've tested this issue against 2.3 and all newer releases. It works in 2.2.2.

I've reproduced this issue locally on my PC with this example http://phaser.io/examples/v2/sprites/move-a-sprite#gv

```javascript
var game = new Phaser.Game(800, 600, Phaser.AUTO, 'phaser-example', { preload: preload, create: create });

function preload() {
    game.load.atlasJSONHash('bot', 'assets/sprites/running_bot.png', 'assets/sprites/running_bot.json');
}

var s;

function create() {
    
    var sb = game.add.spriteBatch(game.world);
    
    s = game.add.sprite(game.world.centerX, game.world.centerY, 'bot', '', sb);
    s.anchor.setTo(0.5, 0.5);
    s.scale.setTo(2, 2);

    s.animations.add('run');
    s.animations.play('run', 10, true);
}
```

**Comment by qdrj** [comment] 2015-08-27 12:01
I've prepared example - http://codepen.io/qdrj/pen/VvZmWZ

**Comment by DDowell** [comment] 2015-10-19 22:25
It seems that preUpdate is not correctly inherited from Phaser.Group but that the default PIXI.DisplayObject.preUpdate is instead called. Thus, the children will not get the preUpdate-call they need to advance the animation. You can patch Phaser yourself by doing this:
```javascript
var spriteBatch = game.add.spriteBatch(game.world);
spriteBatch.preUpdate = function(){
    var i = this.children.length;
    while (i--) {
        this.children[i].preUpdate();
    }
}.bind(spriteBatch);
```

**Comment by qdrj** [comment] 2015-11-07 08:37
@DDowell thank you!
Works like a charm without any side effects.

**Comment by photonstorm** [comment] 2016-02-17 03:24
This is now fixed in dev.

**Closed by photonstorm** 2016-02-17 03:24 UTC

**Comment by Dillybob92** [comment] 2016-03-26 11:53
I'm not sure if I am the only one, but I commented about this issue here: https://github.com/photonstorm/phaser/commit/b6295391761b26aea5f069cadb6b548829efae30#commitcomment-16853934

I applied that patch to my 2.4.3 and now my batches cannot even handle 5k+ images. (Usually 20k+ i no problem). Using the same method the OP has provided in this thread.

I even tested it on 2.4.6 (latest phaser) and the batching is still around a 5k+ limit.  

My regular 2.4.3 version of phaser without the patch applied I can batch thousands of more sprites. This is done without animations on all versions. The commit that I commented on (linked above) is causing the decrease in performance though, the problem is isolated there.  Not sure what else I can do to try to solve this
