### ISSUE TITLE
Arcade.Physics dynamic body can move through static bodies

### ISSUE THREAD

**Issue by alexeymolchan** [photonstorm/phaser#3838] opened 2018-07-15 15:11 UTC
https://monosnap.com/file/QxwRBq0S5i99VVs1QzLLGRj69Tcsur - video of bug / behaviour

https://jsfiddle.net/bzs1urwL/49/ - code example

Maybe problem in this check that i'm doing in update.

```
const {
    up,
    down,
    left,
    right
  } = this.moveKeys;

  if (down.isDown && !up.isDown && this.moving_box.body.velocity.y <= 0) {
     this.moving_box.setVelocityY(350);
  } else if (!down.isDown && up.isDown && this.moving_box.body.velocity.y >= 0) {
     this.moving_box.setVelocityY(-350);
  } else if (down.isDown && up.isDown && this.moving_box.body.velocity.y !== 0) {
     this.moving_box.setVelocityY(0);
  }

  if (left.isDown && !right.isDown && this.moving_box.body.velocity.x >= 0) {
     this.moving_box.setVelocityX(-350);
  } else if (!left.isDown && right.isDown && this.moving_box.body.velocity.x <= 0) {
     this.moving_box.setVelocityX(350);
  } else if (left.isDown && right.isDown && this.moving_box.body.velocity.x !== 0) {
     this.moving_box.setVelocityX(0);
  }
```
Same result with circular body

**Comment by samme** [comment] 2018-07-15 18:05
I think you need to check `body.blocked.*` in the movement logic. <https://jsfiddle.net/p0c1as5x/>

**Comment by alexeymolchan** [comment] 2018-07-15 19:45
@samme i think it doesn't work for circular body

https://monosnap.com/file/HMuD0CFXB248WuXwiip7R6HlxnNAeo

**Comment by oloflarsson** [comment] 2018-07-27 14:16
I don't know if this is related but it seems my dynamic arcade physics bullets can move through static tilemap collission if I shoot them into "the corner" from the right angle: https://gyazo.com/f0d7b64dd96000c4412a55fe88eec148

**Comment by hexus** [comment] 2018-07-30 18:14
@oloflarsson, that's a classic case of tunnelling, which is caused by high velocity bodies moving past a colliding tile into a non-colliding one. It's typically solved by continuous collision detection or predictive collision detection, neither of which are implemented for Arcade as of yet.

**Comment by samme** [comment] 2018-08-03 00:57
@oloflarsson you can adjust [TILE_BIAS](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.World.html#TILE_BIAS__anchor) for that.

**Comment by photonstorm** [comment] 2019-10-02 12:08
Thanks for opening this issue (all those months ago!). Thankfully samme replied with a fix quite soon after, and thanks to a recent update with how circular bodies work in v3, that should now behave properly as well, so I'm going to close this one off.

**Closed by photonstorm** 2019-10-02 12:08 UTC
Labels: 🦔 Need to reproduce
