### ISSUE TITLE
Arc not being striked correctly in Canvas mode

### ISSUE THREAD

**Issue by raisen** [photonstorm/phaser#3965] opened 2018-08-22 00:50 UTC
## Version

* Phaser Version: 3.11.0

* Operating system: OS/X 10.13.6

* Browser:

## Description

I get a different result when I draw an arc in Canvas mode compared to WebGL.

This is the WebGL code:

https://codepen.io/weyseal/pen/JaoMzr

And the Canvas code:

https://codepen.io/weyseal/pen/LJEeae

Any ideas why? 
I have to use Canvas because I have had better performance on mobile devices using it.

**Comment by photonstorm** [comment] 2018-08-22 11:11
This is a duplicate of #3886 so I'm going to close this issue. Please track progress on the issue listed - thank you!

**Closed by photonstorm** 2018-08-22 11:11 UTC

**Comment by Antriel** [comment] 2018-08-22 18:36
Fixed by adding required `beginPath()`: https://codepen.io/anon/pen/vzOyRb
