### ISSUE TITLE
Broken Example: First Lights Example "Blitter Light"

### ISSUE THREAD

**Issue by jppresents** [photonstorm/phaser#4496] opened 2019-04-27 11:22 UTC
## Version

* Phaser Version: 3.16.2 (in example version selection)

* Operating system: Win 10

* Browser: Chrome

## Description

There is no light visible in the example.

## Example Test Code

http://labs.phaser.io/view.html?src=src\game%20objects\lights\blitter%20light.js

## Additional Information

The light becomes visible, when switching to an older phaser version (3.9)

http://labs.phaser.io/view.html?src=src\game%20objects\lights\blitter%20light.js&v=3.9.0

**Comment by schomatis** [comment] 2019-05-17 16:43
I can reproduce this. The `uInverseRotationMatrix` introduced in https://github.com/photonstorm/phaser/pull/4137 is not initialized in the [`Blitter`](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Blitter.html) case, even if it's not needed (because it seems that [`Bob`](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Bob.html) objects can't be rotated, although they can be flipped) it appears it is undefined if `setNormalMapRotation` isn't called.

Adding `this.setNormalMapRotation(0);` in `batchQuad` seems to fix (at least partially) this problem (showing the light), but I don't think this is the correct solution: it seems a bit brittle to explicitilty need to call `setNormalMapRotation` (even with zero) on every function of the kind (like `batchSprite` and `batchTexture`), I think initialization (or pre-processing) ought to be handled a little more upstream if possible.

/cc @sercant who should be able to give a more useful insight than what I just described.

**Comment by photonstorm** [comment] 2020-07-23 16:12
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed by photonstorm** 2020-07-23 16:12 UTC
Labels: 📑 Example
