### ISSUE TITLE
Any way to make "Colored Characters" in Phaser 3?

### ISSUE THREAD

**Issue by kuoruan** [photonstorm/phaser#3428] opened 2018-03-20 09:20 UTC
Phaser 3 removed the function addColor.
https://phaser.io/examples/v2/text/colored-characters

#3223

**Comment by photonstorm** [comment] 2018-03-23 10:21
It wasn't removed, it was just never added. Going to close this as it's a duplicate of #3390 and we can track it in there.

**Closed by photonstorm** 2018-03-23 10:21 UTC
Labels: feature request
