### ISSUE TITLE
particle emitter follow doesn't work correctly with Canvas renderer

### ISSUE THREAD

**Issue by paulsymphony** [photonstorm/phaser#5530] opened 2021-01-27 14:57 UTC
## Version

* Phaser Version:

3.52.0
* Operating system:

* Browser:

## Description

startFollow() results in an offset (x and y) when used with CANVAS renderer. The issue does not occur with WEBGL renderer.

## Example Test Code

Change the demo code here to use Phaser.CANVAS instead of Phaser.AUTO:

https://phaser.io/examples/v3/view/game-objects/particle-emitter/emitter-follow-sprite#

**Comment by photonstorm** [comment] 2021-01-27 15:53
Thanks for opening this issue Paul, but it's a duplicate of #5457 - so please track progress through that issue.

**Closed by photonstorm** 2021-01-27 15:53 UTC
