### ISSUE TITLE
game resize bugged in v3.12.0-beta3

### ISSUE THREAD

**Issue by Antriel** [photonstorm/phaser#3977] opened 2018-08-24 12:10 UTC
## Version
* Phaser Version: 3.12.0-beta3

## Description

Game resizing no longer works.

## Example Test Code

http://labs.phaser.io/view.html?src=src/game%20config\game%20resize.js&v=dev

**Comment by photonstorm** [comment] 2018-08-24 12:25
Yup, still in transition to the SM.

**Comment by photonstorm** [comment] 2018-08-24 12:31
Actually, this is a duplicate of #3928 so going to close this issue to keep the list clean and track progress on the original issue.

**Closed by photonstorm** 2018-08-24 12:31 UTC
Labels: 🐛 Bug (beta)
