### ISSUE TITLE
Phaser.io offline during host investigation

### ISSUE THREAD

**Issue by drneecko** [photonstorm/phaser#5394] opened 2020-11-10 20:05 UTC
What is happened with phaser.io, the website ?

**Comment by spayton** [comment] 2020-11-10 20:37
I noticed labs was unavailable yesterday, thought maybe down for some maintenance, but still down today.

**Comment by photonstorm** [comment] 2020-11-10 20:44
Duplicate of #5392 

The site is down due to an on-going ssh attack. The host is working on it. Should be back soon. Please, no more issues about this.

**Comment by photonstorm** [comment] 2020-11-13 09:47
Host resolved this. Closing.

**Closed by photonstorm** 2020-11-13 09:47 UTC
