### ISSUE TITLE
Tinted BitmapFont updates incorrectly

### ISSUE THREAD

**Issue by Siri0n** [photonstorm/phaser#2850] opened 2016-11-16 13:28 UTC
```js
var game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
	preload: function(){
		game.load.bitmapFont("antiqua", "assets/fonts/Book Antiqua_0.png", "assets/fonts/Book Antiqua.fnt", null, 0, 0);
	},
	create: function(){
		var text = game.add.bitmapText(100, 100, "antiqua", "foobar", 32);
		text.tint = 0xffff;
		setTimeout(function(){
			text.text = "aaaaaa";
		}, 0)
	}
});
```
Result: 
![default](https://cloud.githubusercontent.com/assets/5023794/20349052/9e36508c-ac19-11e6-8504-8e308404de1e.png)

Here's a font for the case it's something wrong with it.
[fonts.zip](https://github.com/photonstorm/phaser/files/594726/fonts.zip)

**Comment by hilts-vaughan** [comment] 2016-11-17 02:36
You're setting text outside of Phaser's game loop -- this is probably asking for trouble.If you use a Phaser Time, does this work properly?

**Comment by Siri0n** [comment] 2016-11-17 05:14
I've encountered this bug while changing bitmapText as a reaction to user input. Then I've tested it, setting text with dev console. I didn't try Phaser.Time, but even if it'll work... well, we still HAVE trouble.

**Comment by hilts-vaughan** [comment] 2016-11-23 03:44
Interesting. We should look into it. :)

**Comment by DDowell** [comment] 2017-02-17 12:02
I have seen this as well in Phaser 2.4.1. If you set a tint on a bitmap text it may not change it's text when you call either the setter (.text) or the function (.setText). What you get is either the old text, a combination of old a new glyphs or the new text. Purging the glyphs doesn't help neither does resetting the tint after you have set the text (not even if you clear the tint before reapplying the tint value).

Prerequisites:
You must have created the game with CANVAS as rendering mode (WEBGL always works).

**Comment by photonstorm** [comment] 2017-02-17 12:52
It was fixed in 2.4.3 (back in August 2015) #1969

When the text is updated it flags all the glyphs as requiring a reTint. When the next render loop runs it picks that up and retints them. If you change the text out of the core game loop, this will be skipped. Working example (from 2.6.2)

```

var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { preload: preload, create: create });

function preload() {

    game.load.bitmapFont('desyrel', 'assets/fonts/bitmapFonts/desyrel.png', 'assets/fonts/bitmapFonts/desyrel.xml');

}

var clicks = 0;
var bmpText;

function create() {

    bmpText = game.add.bitmapText(100, 200, 'desyrel', 'Click me', 64);

    bmpText.inputEnabled = true;

    bmpText.events.onInputDown.add(down, this);

}

function down(item) {

    clicks++;

    item.text = 'You clicked ' + clicks + ' times';

    item.tint = Math.floor(Math.random() * 0xffffff);

}
```

**Comment by DDowell** [comment] 2017-02-17 15:13
It happens in 2.6.1 but only when you set the text more than once. That is, if you create the BitmapText with a text (say XX) and then you set it once to YY it works. However, setting the same BitmapText again to ZZ will sometimes work and sometimes fail (displaying YY or even a strange cropped character).

**Comment by photonstorm** [comment] 2017-02-17 15:21
In the example above the text is reset continuously and works. An example demonstrating this behaviour is needed.

**Comment by DDowell** [comment] 2017-02-19 09:16
[bitmapTextBug.zip](https://github.com/photonstorm/phaser/files/785679/bitmapTextBug.zip)

On each onUp-event I change the text to one of the defined in the array called _someTexts.
Sometimes it works but sometimes the text becomes a mess (for instance, 23.00 becomes 23.0. <= note the erroneous dot). This only happens in CANVAS-mode when a tint is applied.

The Phaser supplied is a build of 2.6.2 taken today from the GitHub repo and built using default settings.

**Comment by DDowell** [comment] 2017-02-19 09:17
Easy way to cause the error to occur is to just mouse over-and-out of the canvas element a couple of times.

**Comment by DDowell** [comment] 2017-02-19 09:30
Bug is reproducable on following systems:
Windows 10 64bit, Chrome 56 & FireFox 51, Nvidia 560ti card.
Windows 10 64bit, Chrome 56, Nvidia 970gtx card.

Haven't yet tried to reproduce on a Mac.

**Comment by SBCGames** [comment] 2017-03-11 19:57
@DDowell - hi, I had the same problem. I created issue in Phaser community repo (https://github.com/photonstorm/phaser-ce/issues/58) as the problem is still present in latest version. There is also how to solve it.

**Comment by samme** [comment] 2017-04-02 22:06
<http://codepen.io/samme/pen/Zewjjo>

**Comment by photonstorm** [comment] 2017-04-20 12:49
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.

**Closed by photonstorm** 2017-04-20 12:49 UTC

**Comment by samme** [comment] 2017-04-20 15:04
Was fixed in <https://github.com/photonstorm/phaser-ce/issues/58>
