### ISSUE TITLE
Disabling anti-alias does not work on Safari

### ISSUE THREAD

**Issue by Legomite** [photonstorm/phaser#4698] opened 2019-08-07 21:23 UTC
## Version

* Phaser Version: 3.18

* Operating system: macOS 10.14.5

* Browser: Safari

## Description

The canvas does not look crisp when anti-aliasing is disabled. In Chrome, disabling anti-alias is functional, but in Safari everything is still blurry.

## Example Test Code

`var config = {
  type: Phaser.AUTO,
  width: document.documentElement.clientWidth,
  height: document.documentElement.clientHeight,
  resolution: window.devicePixelRatio,
  pixelArt: true,
  roundPixels: true,
  antialias: false,`

**Comment by fazzamatazz** [comment] 2019-08-14 20:18
Hi - this is likely due to _resolution_ being disabled in Phaser >3.16 due to other issues.

Probably a duplicate of https://github.com/photonstorm/phaser/issues/4417

**Comment by Legomite** [comment] 2019-08-15 05:17
@fazzamatazz I’ve put this issue as a separate one (which I authored 😛) because disabling anti-alias actually works in Firefox and Chrome running the latest versions of Phaser. The pixels in those browsers are crisp however they’re just a HD version of the low res stuff. For example, small textures have a weird warped appearance.

**Closed** 2019-10-14 15:45 UTC

**Comment by photonstorm** [comment] 2021-05-03 09:08
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/webkit-antialisaing-cannot-be-disabled-3-2x-3-54/9450/1

**Comment by johnedvard** [comment] 2022-05-25 13:43
From the [demo](https://github.com/photonstorm/phaser/issues/4698#issuecomment-541756854), I took one screenshot to compare Chrome (left) with Safari (right)
And it looks like the Safari version is somewhat blurry.
![Screenshot 2022-05-25 at 22 29 45](https://user-images.githubusercontent.com/656024/170275881-96e15891-190d-4f16-93bd-3c9b4824a7f4.png)

It's more noticeable when we use smaller assets such as 16x16px tiles and scale them up. Here's a screenshot from a game I'm working on in Phaser 3.55.2. Comparing Chrome (left) with Safari (right)
![Screenshot 2022-05-25 at 22 41 02](https://user-images.githubusercontent.com/656024/170276377-3f6282dc-9269-491d-8c0c-8bfd934f113f.png)
