### ISSUE TITLE
Get bounds of a container that has a container inside

### ISSUE THREAD

**Issue by PaNaVTEC** [photonstorm/phaser#3660] opened 2018-05-13 13:10 UTC
So basically, when you do this in an `Scene`: 

```
function create() {
  const a = this.add.container(0, 0)
  a.add(new Phaser.GameObjects.Container(this, 0, 0, [
    new Phaser.GameObjects.Text(this, 0, 0, 'Hola', {})
  ]))
  a.getBounds()
}
```

It crashes with:

```phaser.js:56383 Uncaught TypeError: this.parentContainer.getTransformMatrix is not a function
    at Container.getBoundsTransformMatrix (VM395 phaser.js:56383)
    at Text.getBounds (VM395 phaser.js:112194)
    at Container.getBounds (VM395 phaser.js:56278)
    at Container.getBounds (VM395 phaser.js:56278)
    at Scene.create (VM143 pen.js:37)
    at SceneManager.create (VM395 phaser.js:42841)
    at SceneManager.loadComplete (VM395 phaser.js:42735)
    at LoaderPlugin.emit (VM395 phaser.js:1876)
    at LoaderPlugin.loadComplete (VM395 phaser.js:123576)
    at LoaderPlugin.fileProcessComplete (VM395 phaser.js:123532)
```

**Comment by photonstorm** [comment] 2018-05-15 14:07
Duplicate of #3624

**Closed by photonstorm** 2018-05-15 14:07 UTC
Labels: 🐛 Bug, 🤨 Difficulty: Medium
