### ISSUE TITLE
ScaleMode in config object: Cannot read property 'resize' of null

### ISSUE THREAD

**Issue by Mickawesomesque** [photonstorm/phaser#1534] opened 2015-01-11 17:02 UTC
The following code results in a TypeError with Phaser 2.2.2:
```javascript
var conf = {
    height: 960,
    scaleMode: Phaser.ScaleManager.SHOW_ALL,
    width: 640
};

var game = new Phaser.Game(conf);
```
http://jsfiddle.net/gwhq9bhj/

**Comment by pnstickne** [comment] 2015-01-12 06:09
I'm not seeing support for a "config" parameter in dev, which should be past any master release ..

**Comment by pnstickne** [comment] 2015-01-12 06:20
The problem is because the ScaleManager config is being applied before a renderer has been created by the game.

**Comment by pnstickne** [comment] 2015-01-12 15:54
This is actually due to circular and semi-circular dependencies between the ScaleManager and a few other components.

I'm working on a corrective update - say tonight or tomorrow.

**Comment by photonstorm** [comment] 2015-07-08 13:52
This is now fixed in the dev branch.

**Closed by photonstorm** 2015-07-08 13:52 UTC
