### ISSUE TITLE
Sprite Destroy in Group causes rerender

### ISSUE THREAD

**Issue by lunzhang** [photonstorm/phaser#3002] opened 2017-03-21 21:46 UTC
* A bug in the API (v2.6.2)

I have a group containing sprites that move with a negative velocity.  The sprites have checkWorldBounds and is destroyed on onOutOfBounds.  However, when one sprite is destroyed, it causes a twitch in the rest of the sprites.

In the following example, you will see that when the first sprite is destroyed, theres a slight twitch in the second sprite.  I put a console.log on the sprites positions on update, and you will notice that when the first sprite is destroyed, the second sprites.x position is repeated. 

phaser.io/sandbox/mjPHReAl

**Comment by samme** [comment] 2017-03-27 18:45
I think you may be seeing the renderOrderID repeated.

Try it with `sprite.name` instead: http://phaser.io/sandbox/cnGGmiby

**Comment by lunzhang** [comment] 2017-03-27 19:32
there's still a twitch in the rendering, you'll see it if you change the velocity to -100, also after sprite 0 is destroyed, sprite 1 position x is repeated in the logs,

**Comment by samme** [comment] 2017-03-28 19:30
I think I see what you mean: <http://codepen.io/samme/pen/MpqzPg>

The problem is actually that the sprite following the destroyed one misses its preUpdate call, so for one frame it fails to advance.

In your case you can work around the problem by calling `kill` instead of `destroy`; then destroy dead sprites (if you need to) during `update`.

**Comment by lunzhang** [comment] 2017-03-28 19:38
I decided to use kill instead of destroy.  However, it's still a bug that the following sprite misses a frame.

**Comment by samme** [comment] 2017-04-04 17:02
https://github.com/photonstorm/phaser-ce/issues/103

**Comment by photonstorm** [comment] 2017-04-20 13:01
Fixed in Phaser CE, so closing it off here.

**Closed by photonstorm** 2017-04-20 13:01 UTC
