### ISSUE TITLE
Camera move + tiledmap + running mobile

### ISSUE THREAD

**Issue by MrDallOca** [photonstorm/phaser#2279] opened 2016-01-04 16:35 UTC
I've tried make a game with tiledmap and camera following just like many examples. It worked beautifully in my pc. The problem is that the camera really doens't work when running mobile. Is there an easy way to fix it? If not, please do it soon as possible

**Comment by Teelord** [comment] 2016-01-04 21:32
This looks like a duplicate of [this issue](https://github.com/photonstorm/phaser/issues/2273)

**Comment by MrDallOca** [comment] 2016-01-04 22:36
Actually, the problem is not just lagging, but the camera completely stops. So I thought it would be good to open a new issue report

**Comment by Jonp713** [comment] 2016-01-05 03:40
This is a different issue. My camera is in the top left corner to start

**Comment by MrDallOca** [comment] 2016-01-05 09:43
So do mine

**Comment by Teelord** [comment] 2016-01-05 14:38
Interesting. For me, on scroll, the fps drops to about 5. This occurs no matter where in the map the camera is. I'm going to try the same code against recent (but older) versions of Phaser to hopefully see when the regression took place.

**Comment by MrDallOca** [comment] 2016-01-05 19:39
I'm using phaser 2.4.4, android lollipop

**Comment by danbolt** [comment] 2016-01-13 14:47
Is your code using the WebGL renderer, or Canvas? I find that WebGL on mobile with tilemaps can have some slowdown. I think this is due to the way Phaser and PIXI.js cache tilemaps.

**Comment by MrDallOca** [comment] 2016-01-15 01:04
Hmmmm... I'm almost sure I was using WebGL. But I think Canvas it's not as fast as WebGl, specially when running with Cordova in a mobile device.

**Comment by photonstorm** [comment] 2016-02-04 16:39
Closing this because it's subjective, with no code example to test against, and no test environment details provided.

**Closed by photonstorm** 2016-02-04 16:39 UTC
