### ISSUE TITLE
TileSprite loadTexture crash

### ISSUE THREAD

**Issue by pandavigoureux29** [photonstorm/phaser#1495] opened 2014-12-30 20:22 UTC
I want to load a texture 
tilesprite.loadTexture("imageName");

With sprites, it works fine. But with tilesprites, it crashes : 
Uncaught TypeError: undefined is not a function at phaser.js 10857
 
I went to phaser.js to see the line that looks like this :
PIXI.updateWebGLTexture(this.tilingTexture.baseTexture, renderSession.gl);

It seems that PIXI.updateWebGLTexture is undefined ! ( I console.log it )
Just so you know, I'm in WebGL mode.

**Comment by pnstickne** [comment] 2015-01-05 04:51
@pandavigoureux29 
This is a PIXI regression. There is indeed no more `PIXI.updateWebGLTexture` and this part of pixi has not been updated. (It could also be fixed in a later pixi head/dev version.)

Consider posting the issue to https://github.com/GoodBoyDigital/pixi.js/issues, if it has not already been done.

**Comment by photonstorm** [comment] 2015-01-05 10:03
I wouldn't bother, it looks like they've stopped fixing bugs in an attempt to break Pixi up into modules. That's going to take a while (and will make it incompatible with Phaser) so from now on I'm happy to fix Pixi issues directly in the Phaser source, which will include this.

**Comment by photonstorm** [comment] 2015-01-05 19:01
This is now fixed in dev branch.

**Closed by photonstorm** 2015-01-05 19:01 UTC
Labels: pixi bug
