### ISSUE TITLE
width is not defined at SpriteSheetFromAtlas.js:66

### ISSUE THREAD

**Issue by mindcity** [photonstorm/phaser#3079] opened 2017-10-28 06:53 UTC
Phaser 3.0.0-beta.7

When I followed the example of `PHASER3-EXAMPLES/src/textures/sprite sheet from atlas.js`, the browser throws an error
```
SpriteSheetFromAtlas.js:66 Uncaught ReferenceError: width is not defined
    at Object.SpriteSheetFromAtlas (VM15735 dev.js:54125)
    at TextureManager.addSpriteSheetFromAtlas (VM15735 dev.js:53588)
    ...
```

**Comment by photonstorm** [comment] 2017-11-01 22:24
Yeah, this feature is in a bit of a mess and needs finishing off. The issue is with sprite sheets within trimmed texture atlases. Outside of that it worked ok, but enable trim (like you nearly always do with an atlas) and it screws up.

**Comment by photonstorm** [comment] 2017-11-03 13:19
This is now fixed in the master branch. Sprite sheets work correctly when embedded within texture atlases, with or without atlas trim, padding, borders, etc enabled. New example showing it in action added.

**Closed by photonstorm** 2017-11-03 13:19 UTC
Labels: bug (phaser)
