### ISSUE TITLE
this.game.renderer.snapshot  move the canvas 1px down

### ISSUE THREAD

**Issue by gammafp** [photonstorm/phaser#4956] opened 2020-01-15 16:13 UTC
[Spanish]
Cuando tratas de obtener una imagen desde el canvas en webGL hay un error al tratar de hacer snapshot al renderer: La imagen resultante está movida 1px hacía abajo.

Este error no ocurre en el modo CANVAS de Phaser.

[English]
When you want get a image from canvas in webGL there is a error in renderer snapshot, the image down 1px.

This error does not occur on Phaser.CANVAS type.

[error_webgl.zip](https://github.com/photonstorm/phaser/files/4065902/error_webgl.zip)
![Captura](https://user-images.githubusercontent.com/9221946/72450162-2dcbd800-37ba-11ea-9cc3-f141c0463911.PNG)

**Comment by telinc1** [comment] 2020-01-21 12:12
This is caused by an oversight when determining a pixel's index in the OpenGL buffer in [`WebGLSnapshot`](https://github.com/photonstorm/phaser/blob/master/src/renderer/snapshot/WebGLSnapshot.js#L72). Changing line 72 to `var sourceIndex = ((height - py - 1) * width + px) * 4;` should fix this, but I haven't tested it thoroughly enough to make a PR.

**Comment by photonstorm** [comment] 2020-09-24 09:33
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed by photonstorm** 2020-09-24 09:33 UTC
Labels: 🔮 Renderer (WebGL)
