### ISSUE TITLE
IOS/Android - Chrome - Visibility Change not firing

### ISSUE THREAD

**Issue by nickryall** [photonstorm/phaser#1101] opened 2014-08-09 21:40 UTC
Seen in Chrome on IOS 7.1 and Android 4.42. Minimising the browser does not pause the game. Audio is not muted.

**Comment by B3nac** [comment] 2015-03-04 04:06
Tested sound muting on minimized Chrome browser on Android 5.0 and it works. Maybe Android 4.42 specific? Android just yesterday updated to 5.0.

**Comment by photonstorm** [comment] 2016-02-04 15:39
Closing due to OAP status and unable to currently reproduce.

**Closed by photonstorm** 2016-02-04 15:39 UTC
Labels: needs checking
