### ISSUE TITLE
Timeline bug?

### ISSUE THREAD

**Issue by MadDogMayCry0** [photonstorm/phaser#5335] opened 2020-10-01 11:36 UTC
3.24.1
https://playcode.io/683803

I noticed that my character often twitches when moving. At first I attributed this behavior to small browser freezes, but then I noticed that when a character twitches, other characters that animate without using timeline continue to run smoothly.

I made a small preview. I don’t know, maybe I’m doing something wrong.

**Comment by photonstorm** [comment] 2022-08-22 23:13
Duplicate of #5144 (just tidying up as I refactor Timelines)

**Closed by photonstorm** 2022-08-22 23:13 UTC
Labels: ⏱️ Tween / Timeline
