### ISSUE TITLE
Performance degradation from v2.1.3 to v2.2.0

### ISSUE THREAD

**Issue by SVasilev** [photonstorm/phaser#2102] opened 2015-09-21 13:10 UTC
Okay, so I have this little game here:
https://github.com/SVasilev/FinalFantasy1JS
It's still in development so the code is kind of messy. Anyway you can start the game by clonning it from github, run ```npm install```, then run ```node server.js ``` in the root directory (you need to have Nodejs installed) and then go into your browser on localhost:8080. If you start to move north on the map it is great and smooth. Okay so now go to index.html and change phaser version from 2.1.3 to 2.2.0 and reload the page. Move north and around for 20-30 seconds, then the game starts to lag. It is tested on latest Chrome.
I've read your guidelines for contributing and I know this is not an isolated problem, for which I am sorry, but I can't seem to find a way to make it more isolated scenario. Anyway I think the reproduction of the problem can be done in 2-3 minutes which is not that bad.
Best Regards,
Stefan

**Comment by photonstorm** [comment] 2015-09-21 14:08
This needs testing against 2.4.4 really. 2.2 is too old to be considered a useful benchmark any longer. There was also a significant version upgrade of Pixi between 2.1.3 and 2.2.

**Comment by SVasilev** [comment] 2015-09-21 15:44
Yes, I tested all the versions between 2.1.3 and 2.4.4, which you tagged in your github repo. It seems this behavior comes with the switch 2.1.3->2.2.0. I forgot to mention that. Note: I cant seem to find a link for 2.4.4 min js. Can you give me so I can try this against 2.4.4, although I dont think that the lag will disappear.

**Comment by pnstickne** [comment] 2015-09-22 03:38
@SVasilev  'dev' is currently '2.4.4-beta'; 2.4.3 is last release.

**Comment by pnstickne** [comment] 2015-09-22 05:07
Confirmed that there is some 'intermittent lag' in Post 2.1.3 builds.

On my system the lag is only momentary (but keeps recurring) making me believe it's related to some GC thrashing..

Likely related to a PIXI change since the game works be panning around a large (4k x 3k) scaled image, which probably doesn't help'.

**Comment by photonstorm** [comment] 2016-02-04 12:46
I appreciate the time taken to open this issue but I'm afraid I'm closing it. I sadly cannot spend time looking at issues that are differences between vast spans of Phaser and Pixi versions. If the issue is an actual bug then I've something to focus on, but alas this isn't the case here.

**Closed by photonstorm** 2016-02-04 12:46 UTC

**Comment by SVasilev** [comment] 2016-02-05 08:30
Just to make sure I understood correctly, the problem is with Pixi objects? So should you or me open a bug there, because I think this is a big performace degradation.

**Comment by photonstorm** [comment] 2016-02-05 10:39
No because it's not a fair issue to open for Pixi either, and they are 2 _major_ versions ahead of the one that Phaser 2.1.3 was using so wouldn't look at it anyway.

Understand it from our point of view - there's nothing here to debug, nothing _isolated_, just a sprawling game. It could take us days to boil that down into something actionable. If it runs better in an earlier version, use the earlier version.

**Comment by SVasilev** [comment] 2016-02-05 14:50
Would you be interested in reviewing the problem if I can isolate it in 10-15 lines of code with the newest Phaser version?

**Comment by photonstorm** [comment] 2016-02-05 16:10
Yes of course.

**Comment by photonstorm** [comment] 2016-02-05 16:11
And it doesn't even have to be 15 lines... 100 lines of code is fine, what is important is that it's an isolated case with as minimum of extra fluff as possible. Just what is needed to demonstrate the issue.

**Comment by SVasilev** [comment] 2016-02-05 20:52
Hello,
I managed to isolate the problem. Here you go, 2 files, 40 lines ;)
[performanceBug.zip](https://github.com/photonstorm/phaser/files/119855/performanceBug.zip)
Regards,
Stefan

**Comment by photonstorm** [comment] 2016-02-06 17:14
I'll take a look at this. Also I'd be interested to know if the new Phaser 2.5 + Pixi 3 build makes a difference to you (available here: https://github.com/photonstorm/phaser/tree/pixi3/build)

**Comment by SVasilev** [comment] 2016-02-08 18:35
Sorry for the slow reply. Unfortunately the problem still persists.

**Comment by photonstorm** [comment] 2016-02-08 22:53
Have tested this under Phaser 2.4.5 and 2.5 with Pixi v3 and in both cases, in Canvas and WebGL mode, I can leave it scrolling indefinitely with no slow-down. I set it up to auto-scroll and left it going for 2 minutes in each case. I _do_ get periodic stuttering, but I'd expect that because of what's going on under the hood (see below) and the fact it's being scrolled with no delta smoothing, so lags as gc sweeps will be exaggerated.

Some observations:

The texture is insanely huge. It has to create a Canvas Tile Pattern from this massive image, then fill in a 1280 x 720 area with it, _every single frame_. So up to 60 times per second. That's a _lot_ of pixels to be pushing, even for gaming grade hardware.

Equally the gc will kick in because it has to erase all those thousands of tile patterns that are being created and then no longer used. This will absolutely result in frame stutters every time the gc sweeps (on my Mac that's approximately every 20 seconds looking at it).

In WebGL mode it doesn't have to do this, but the texture is so large it may not even fit into low-end GPU texture memory anyway, forcing it out to software and instantly slowing it down as it thrashes memory.

Frankly I'm amazed even Phaser 2.1.3 managed this - but what I think you're seeing there is the old 'no delta timer' method of the frame update loop running, which you can emulate under 2.4 via `game.forceSingleUpdate = true`.

**Comment by SVasilev** [comment] 2016-02-09 22:01
Thank you very much.
I think this solved the problem. This issue can be closed.
Pretty interesting though. Shouldn't this property value be true by default?
Stefan
