### ISSUE TITLE
Phaser.ScaleManager#fullScreenChange / game.camera.bounds = null

### ISSUE THREAD

**Issue by prudolfs** [photonstorm/phaser#2099] opened 2015-09-20 01:21 UTC
I'm setting camera bounds to null. Which as far as I understand is valid. But then problem arrives on fullscreen exit.

Uncaught TypeError: Cannot read property 'copyFrom' of null.
Camera.setBoundsToWorld
World.resize
ScaleManager.updateDimensions
ScaleManager.prepScreenMode
ScaleManager.fullScreenChange
ScaleManager.boot.compatibility.supportsFullScreen._fullScreenChange

**Comment by pnstickne** [comment] 2015-09-20 04:55
What problem is encountered? The issue is unclear from the posted entry.

Also, what version of Phaser is used?

Creating a minimal runnable example (eg. codepen, phaser sandbox) that demonstrates the problem would be a great help.

**Comment by prudolfs** [comment] 2015-09-20 15:11
Sorry. Please try to run reproducible example http://codepen.io/prudolfs/pen/BozKRm and you will get Uncaught TypeError: Cannot read property 'copyFrom' of null.

**Comment by prudolfs** [comment] 2015-09-20 17:11
This problem still persists in phaser 2.4.4 dev. Of course I can patch things. But then I don't know whether it safe.

```javascript
Phaser.Camera.prototype.setBoundsToWorld = function () {
	
	if (this.bounds) {

		this.bounds.copyFrom(this.game.world.bounds);

	} else {

		// I don't want else, because it'll break my game logic

	}

}
```

**Comment by photonstorm** [comment] 2015-09-20 20:08
Fixed in dev.

**Closed by photonstorm** 2015-09-20 20:08 UTC
