### ISSUE TITLE
The controll of xbox360 does not work correctly

### ISSUE THREAD

**Issue by gammafp** [photonstorm/phaser#4423] opened 2019-03-12 19:43 UTC
In this example:
https://labs.phaser.io/view.html?src=src/input\gamepad\select%20gamepad.js&v=dev
The controller of xbox360 (wireless) does not work only work in Phaser 3.14 in phaser 3.16.2 only work if you move or click down the mouse.

**Comment by GaryStanton** [comment] 2019-03-12 19:46
I have the same issue. It's working for me up til 3.15, but no input on 3.16.
I have a wired 360 controller.

**Comment by benjimmy** [comment] 2019-03-20 07:58
the input:{queue:true} config input compatibility mode fixes this for now

**Comment by photonstorm** [comment] 2019-04-05 17:25
Duplicate of #4414 - please track progress on that issue.

**Closed by photonstorm** 2019-04-05 17:25 UTC
