### ISSUE TITLE
Can't use phaser with npm/browserify:  PIXI not defined 

### ISSUE THREAD

**Issue by Deftwun** [photonstorm/phaser#2424] opened 2016-04-09 16:06 UTC
Using version 2.4.6 through npm. I get this error:
```bundle.js:23178 Uncaught ReferenceError: PIXI is not defined``` 

Looks like [PIXI not defined here ](https://github.com/photonstorm/phaser/blob/master/src/Phaser.js#L364) in Phaser.js.

I also tried pulling from the master repo, npm install, grunt build, and just used require on the compiled phaser.js file but had the exact same problem.

**Comment by drhayes** [comment] 2016-04-09 17:21
Dupe of #2131.

**Comment by mattstyles** [comment] 2016-04-12 07:18
I'm trying to have a quick look at making Phaser work with browserify and have all the dependencies for my projects in one place as it would work better with the rest of my toolchain but I think Rich and other have already intimated that it is not a trivial fix to support CJS modules. Not sure if Lazer is already set up to support CJS or not.

**Comment by Deftwun** [comment] 2016-04-13 13:44
@mattstyles Yup seems to work great for me thanks!

**Comment by photonstorm** [comment] 2016-04-13 15:07
This has been added to the README.

**Closed by photonstorm** 2016-04-13 15:07 UTC

**Comment by mattstyles** [comment] 2016-04-13 16:03
I'd say you could add a caveat in there about not fighting with CJS stuff and just include Phaser as a global, and use browserify-shim if you like to `require( 'Phaser' )` in your code, but, honestly, it's wordy enough. I'm not sure you should add another paragraph explaining how to use globals with browserify, thats up for users to work out from the browserify end.
