### ISSUE TITLE
Tween#seek before tween init

### ISSUE THREAD

**Issue by renan-ti** [photonstorm/phaser#4210] opened 2018-12-04 05:33 UTC
## Version
* Phaser Version: 3.15.1

## Example Test Code

Paste on https://labs.phaser.io/edit.html :

```
var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create,
    }
};
var game = new Phaser.Game(config);

function preload () {
    this.load.image('block', 'assets/sprites/block.png');
}

function create () {
    var image = this.add.image(200, 300, 'block');
    var tween = this.tweens.add({
        targets: image,
        props: {
            x: { value: '600', duration: 10000 },
        }
    });
    tween.seek(0.5);
}
```

## Additional Information

Without the tween.seek line, the animation starts from x = 200 to 600 in 10s. With the tween.seek line:
* Expected behaviour: animation from 400 to 600 in 5s;
* Actual behaviour: animation from 0 to 600 in 10s.

**Comment by photonstorm** [comment] 2019-01-24 14:36
Duplicate of #3517 - please track progress there.

**Closed by photonstorm** 2019-01-24 14:36 UTC
Labels: 🐛 Bug
