### ISSUE TITLE
TileSprite.setSize causes error in updateCanvas

### ISSUE THREAD

**Issue by goldfire** [photonstorm/phaser#3944] opened 2018-08-17 21:15 UTC
## Version

* Phaser Version: 3.12.0-beta2

* Operating system: macOS 10.13.5

* Browser: Chrome 68.0.3440.106

## Description

Changing the width/height of a TileSprite either by directly setting width/height or by calling the `setSize` method, causes the below error to occur.

```
Uncaught TypeError: this.frame.resize is not a function
    at TileSprite.updateCanvas (VM2501 dev.js:58532)
    at TileSpriteWebGLRenderer [as renderWebGL] (VM2501 dev.js:58922)
    at WebGLRenderer.render (VM2501 dev.js:131363)
    at CameraManager.render (VM2501 dev.js:11713)
    at Systems.render (VM2501 dev.js:138337)
    at SceneManager.render (VM2501 dev.js:135910)
    at Game.step (VM2501 dev.js:6657)
    at TimeStep.step (VM2501 dev.js:7765)
    at step (VM2501 dev.js:26793)
```
This error is pointing towards `Phaser.GameObjects.TileSprite.updateCanvas`, and specifically the line `this.frame.resize(this.width, this.height);`. Commenting out this line fixes the issue, but I'm not sure if this was there for a reason and just has something wrong with the implementation.

**Comment by photonstorm** [comment] 2018-08-19 16:36
Thanks for reporting this. It's actually a duplicate of #3913 (even though the title of that issue is incorrect, the bug is the same, so please track the fix from there)

**Closed by photonstorm** 2018-08-19 16:36 UTC

**Comment by photonstorm** [comment] 2018-08-20 16:07
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by goldfire** [comment] 2018-08-21 19:29
I can confirm it is fixed, thanks!
