### ISSUE TITLE
Bug with graphic elements

### ISSUE THREAD

**Issue by magnusducatus** [photonstorm/phaser#3898] opened 2018-08-07 13:47 UTC
When i opened my app on mobile phone i seen this. Maybe you can answer why?
![bug](https://user-images.githubusercontent.com/36621409/43779486-2d77ae94-9a61-11e8-875a-992fee4ebe5a.png)

**Comment by photonstorm** [comment] 2018-08-07 13:48
Can't debug screenshots.

**Comment by magnusducatuslt** [comment] 2018-08-07 13:55
When i open my app on PC, its okey. But when i open on mobile phone, i had this problem. I didnt undestand how explaine this bug technicalese.
This is example of code. 

class ProgressBar extends Phaser.GameObjects.Container {
  constructor(scene, type = HEALTHBAR, currentValue = 100, maxValue = 100, width, height, isTextCentered = false) {
    super(scene);
    this.scene = scene;
    this.type = type;
    this.currentValue = currentValue;
    this.maxValue = maxValue;
    this.updateTween = null;
    this.isTextCentered = isTextCentered;
    this.root = this.scene.make.graphics();
    this.progress = this.scene.make.graphics();
    if (progressBarStyles[this.type].icon) {
      this.icon = this.scene.make.image({ key: ATLAS_FOR.BATTLE, frame: progressBarStyles[this.type].icon.key });
      //this.icon = this.scene.make.image({ key: progressBarStyles[this.type].icon.key });
    }
    this.text = this.scene.make.text({ fontFamily: 'Arial', color: '#ffffff', fontStyle: 'bold' });
    this.text.resolution = window.devicePixelRatio || 1;
    this.text.setOrigin(1, 0.5);
    this.text.setShadow(2.8, 2.8, 'rgba(0, 0, 0, 25)', false, true);
    this.text.setFontStyle('bold');
    this.text.setScale(0.5);
    const textValue = this.type !== RANKBAR ? `${currentValue}/${maxValue}` : `${currentValue}/${maxValue} XP`;
    this.text.setText(textValue);
    //this.boot(false, width, height);
    this.boot(false);
    const baseChilds = [this.root, this.progress, this.text];
    this.add(this.icon ? baseChilds.concat(this.icon) : baseChilds);
    this.scene.add.existing(this);
  }
  //boot = (isResize = false) => {
  boot = (isResize = false, width, height) => {
    if (this.updateTween) {
      this.updateTween.pause();
    }
    console.log(healthBarDimensions.width, healthBarDimensions.height);
    const containerWidth = width || getResizedWidth(630.5);
    //const containerHeight = height || getResizedHeight(10);
    const containerHeight = height || getResizedHeight(10);
    // this.setSize(
    //   getResizedWidth(healthBarDimensions.width),
    //   containerHeight < 34 && this.type !== RANKBAR ? 34 : containerHeight
    // );
    this.setSize(containerWidth, containerHeight < 34 && this.type !== RANKBAR ? 34 : containerHeight);
    this.innerWidth = this.width - this.height * 0.09;
    this.innerHeight = this.height - this.height * 0.09;
    this.createRoot(isResize);
    this.createProgress(isResize);
    if (this.icon) {
      this.rescaleIcon();
    }
    this.setupTextStyles();

    if (this.updateTween) {
      this.updateTween.resume();
    }
  };

  createRoot = (withClear = false) => {
    if (withClear) {
      this.root.clear();
    }
    const offset = this.height * 0.045;
    this.root.fillStyle(0x000000, 0.3);
    this.root.fillRect(offset, offset, this.innerWidth, this.innerHeight);
    this.root.lineStyle(this.height * 0.09, progressBarStyles[this.type].borderColor, 1);
    this.root.strokeRoundedRect(0, 0, this.width, this.height, this.height * 0.125);
  };

  createProgress = (withClear = false) => {
    if (withClear) {
      this.progress.clear();
    }
    const valuesAspect = this.getValuesAspect();
    if (valuesAspect === 0) {
      return;
    }
    const borderBaseRadius = this.innerHeight * 0.076;
    const borders = {
      tl: borderBaseRadius,
      bl: borderBaseRadius,
      br: valuesAspect < 1 ? 0 : borderBaseRadius,
      tr: valuesAspect < 1 ? 0 : borderBaseRadius
    };

    const offset = this.height * 0.045;
    const shadowOffset = this.innerHeight * 0.076;
    this.progress.fillStyle(progressBarStyles[this.type].progressShadowColor, 1);
    this.progress.fillRoundedRect(offset, offset, this.innerWidth * valuesAspect, this.innerHeight, borders);
    this.progress.fillStyle(progressBarStyles[this.type].progressColor, 1);
    this.progress.fillRoundedRect(
      offset,
      offset,
      this.innerWidth * valuesAspect,
      this.innerHeight - shadowOffset,
      borders
    );
  };

  rescaleIcon = () => {
    const { heightPercentage, dimensionsAspect } = progressBarStyles[this.type].icon;
    const iconHeight = this.height * heightPercentage;
    const iconWidth = this.height * heightPercentage * dimensionsAspect;

    this.icon.setScale(iconWidth / this.icon.width, iconHeight / this.icon.height);
    this.icon.setPosition(iconWidth / 2 + this.innerWidth * 0.02, this.height / 2 - 2.5);
  };

  setupTextStyles = () => {
    this.text.setFontSize(this.height * 0.55 * 2);
    this.text.setPosition(
      this.isTextCentered ? this.width / 2 + this.text.displayWidth / 2 : this.width - 10,
      this.height / 2
    );
  };
  // resize = () => {
  //   this.boot(true);
  // };
  resize = (width, height) => {
    this.boot(true, width, height);
  };

  getValuesAspect = () => {
    return this.currentValue / this.maxValue;
  };
  //updateHealthbar = nextValue => {
  updateProgress = nextValue => {
    if (this.updateTween) {
      this.updateTween.stop();
    }
    if (nextValue >= 0) {
      this.updateTween = this.scene.add.tween({
        targets: this,
        currentValue: nextValue,
        onUpdate: tween => {
          const nextCalculatedValue = tween.data[0].current;
          const textValue =
            this.type !== RANKBAR
              ? `${Math.round(nextCalculatedValue)}/${this.maxValue}`
              : `${Math.round(nextCalculatedValue)}/${this.maxValue} XP`;
          this.text.setText();
          //this.text.setText(textValue);
          this.createProgress(true);
        },
        onComplete: () => {
          this.updateTween = null;
        },
        duration: 200,
        ease: 'Linear'
      });
    }
  };
}

**Comment by iamchristopher** [comment] 2018-08-07 15:09
@magnusducatuslt Not to speak out of turn, but in cases like this it's much easier to help diagnose with a live, running sample. I'd recommend getting this running on a service like jsfiddle so others can be certain they're viewing the same issue you are.

**Comment by hexus** [comment] 2018-08-17 11:46
@magnusducatus, as mentioned above, please provide a simplified, running example of the issue.

**Comment by photonstorm** [comment] 2018-08-23 11:39
This issue is the same as #3955 - although I appreciate that you opened this issue first (so technically 3955 is a duplicate of this), that one provides a more solid test case, so I'm going to close this and please ask that you track 3955 instead. Also, please test against the master branch, as I pushed a fix up today that should solve this.

**Closed by photonstorm** 2018-08-23 11:39 UTC
Labels: 👩‍💻 Code example needed, 🤷‍♂️ More info needed
