### ISSUE TITLE
IE10 Texture Error: frame does not fit inside the base Texture dimensions

### ISSUE THREAD

**Issue by DrHackenstein** [photonstorm/phaser#1128] opened 2014-08-21 21:42 UTC
I've just found out that in IE 10.0.9200.16798 Phaser v2.0.7 seems to have problems loading certain sprite sheets. I'm not sure what's exactly causing the problem as there are not all, but a couple of images affected. This error does not occur on IE11, apparently.
SCRIPT5022: Texture Error: frame does not fit inside the base Texture dimensions [object Object] 
phaser.js, line 11139 character 9

I'm on the run and can't provide a better description or examples. However you can test it with our game: http://hypnoticowl.com/play/thewizard/  
The first image that's affected is http://hypnoticowl.com/play/thewizard/assets/interface/spellbook/ribbons.png
which is loaded like this: this.game.load.spritesheet('ribbons', 'assets/interface/spellbook/ribbons.png', 88, 52);

**Comment by photonstorm** [comment] 2015-02-10 13:56
I've retested this just now under 2.3-dev and I'm still unable to reproduce the error in any browser I throw it at. Going to close this off for now - that's not to say I don't believe it happens (clear it does), but am going to need a consistent test case, or some parameters to help define the cause, before it can be addressed.

**Closed by photonstorm** 2015-02-10 13:56 UTC
Labels: please test

**Comment by r-daneelolivaw** [comment] 2015-11-19 14:01
Despite the fact that this comment is closed, it may be interesting to know that I managed to reproduce this on 2.3 stable on IE10 only. After running unit and stress tests, it appeared that it is only related to the amount of spritesheets (at a given point, it is not possible to load another one). IE yields this error "Texture Error: frame does not fit inside the base Texture dimensions [object Object] ", that is inconsistent because it is related to a performance issue of IE.

**Comment by evgeniy-polyakov** [comment] 2016-01-15 07:31
I got same issue in IE10 with large spritesheet (40 frames). The problem is in 'for' loop in spritesheet parser: https://github.com/photonstorm/phaser/blob/master/src/animation/AnimationParser.js#L76. IE10 optimizes that loop some way and in result 'x' is always incremented and never reset back to 'margin'. The workaround is using a local object {x,y} instead of local variables x,y. I know that's a kind of magic but it works for me. Should I register a pull request with this fix?
