### ISSUE TITLE
Tween and smoothed bug

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2086] opened 2015-09-13 23:04 UTC
I've found a very interesting bug today. When you tween a Phaser.Image (it likely happens on Sprites too), the tween will mess with the images .smoothed property. It sounds unlikely, but I've tested it again and again. If I create an image, set the smoothed property to true and tween it, the smoothed property will sometimes (randomly) turn to false mid-tween. You may need to create multiple images with multiple tweens to see it happen. And it happens randomly, but it does happen consistently.  

var amountRotation = 5; 
var tween = game.add.tween(tree).to({
        angle: amountRotation,
}, 5000, Phaser.Easing.None, true, 0, -1, true);

tween.onUpdateCallback(function() {
console.log(tree.smoothed); // you can watch it randomly change to false!
}, this); 

If you set the smoothed property to true in the update callback, the problem goes away because it overrides whatever is happening internally to mess with the smoothed property.

**Comment by pnstickne** [comment] 2015-09-13 23:15
Which version of Phaser?
Also, can you generate a reproduction case (ie. in http://phaser.io/sandbox or codepen)?

**Comment by photonstorm** [comment] 2015-09-14 09:36
Hmm strange - no-where will the tweens ever directly change the smoothed property. So the only thing that could happen is it thinks it needs to tween it. You said it happens mid-tween, which to me indicates maybe at the yoyo point where it begins to reverse. Does it happen if you don't yoyo it?

**Comment by cscott5288** [comment] 2015-10-04 19:54
It happens with or without yoyo. If I look at the Phaser.Image object in the console and examine the prototype, I notice that the smoothed property gives this:

TypeError: Cannot read property 'baseTexture' of undefined at Phaser.Component.Smoothed.smoothed.get (/game/js/libraries/phaser-2.3.0.js:36368:33) at remoteFunction (<anonymous>:3:14) at Object.InjectedScript.callFunctionOn (<anonymous>:750:66)

**Comment by photonstorm** [comment] 2016-02-04 12:39
Closing this because I cannot reproduce it, and without a test case demonstrating it I can't even start to figure out what may cause it, or how to fix it, sorry.

**Closed by photonstorm** 2016-02-04 12:39 UTC

**Comment by ForgeableSum** [comment] 2016-04-07 16:40
The problem was fixed in this issue:
https://github.com/photonstorm/phaser/issues/2317
