### ISSUE TITLE
Custom shader on camera flips Y

### ISSUE THREAD

**Issue by gabebond** [photonstorm/phaser#5167] opened 2020-05-25 18:23 UTC
When you add a custom shader on a sprite object AND a camera, that custom shaded sprite is flipped vertically. I posted the issue on your forums: https://phaser.discourse.group/t/custom-shader-on-camera-flipy/6435

code:
var config = {
  type: Phaser.WEBGL,parent: 'phaser-example',width:500,height:500,
  scene: {preload: preload,create: create}
};

var game = new Phaser.Game(config);
function preload() {
  this.load.image('atari', 'assets/sprites/atari400.png');
  this.game.renderer.addPipeline("custom",
  new Phaser.Renderer.WebGL.Pipelines.TextureTintPipeline({
    game:game,
    renderer:game.renderer
  }));
}

function create() {
  this.add.sprite(150, 100, 'atari').setPipeline('custom')
  this.add.sprite(350,100,"atari")
  this.cameras.main.setRenderToTexture("custom");
}

screenshot:
https://aws1.discourse-cdn.com/free1/uploads/phaser1/optimized/2X/3/300b00982af523e2967de51c739ad630ee582919_2_573x375.png

**Comment by photonstorm** [comment] 2020-09-02 21:12
Thanks for opening this, however, it is a duplicate of #4158 so I'm closing this. Please follow progress in the other issue.

**Closed by photonstorm** 2020-09-02 21:12 UTC
