### ISSUE TITLE
Mute sound still plays first milliseconds of the next sound

### ISSUE THREAD

**Issue by jaapaurelio** [photonstorm/phaser#2468] opened 2016-05-06 12:10 UTC
This Issue is about
- A bug in the API

This happens when we play a button sound, click mute, and play button sound again. The first milliseconds of the sound will be played.

Steps to reproduce.
1 - Click button_sound
2 - Wait 2 seconds
3 - Click mute_button
4 - Wait 2 seconds
5 - Click button_sound
6 - You will hear the beginning of the button sound.

I'm using this sound as `button_press.wav`:
https://www.freesound.org/people/MultiMax2121/sounds/156859/
This is also happening with other sounds that start at 00:00.

Here is the code:

``` javascript
var game;   
window.onload = function () {
  game = new Phaser.Game();

  game.state.add('play', Play);
  game.state.start('play');
};


function Play() {}
Play.prototype = {
    preload: function() {
        this.load.audio('button_press', 'button_press.wav');
        this.load.image('button_sound', 'button_sound.png');
        this.load.image('button_mute', 'button_mute.png');
    },

    create: function() {
        var that = this;
        this.clickSound = game.sound.add('button_press');

        this.muteButton = game.add.button(100, 100, 'button_mute', function(){
            if(this.game.sound.mute) {

                this.game.sound.mute = false;
                this.game.sound.volume = 1;

            } else {

                this.game.sound.mute = true;
                this.game.sound.volume = 0;

            }

        }, this)

        this.muteButton = game.add.button(400, 100, 'button_sound', function(){
            this.clickSound.play();
        }, this)
    }
};
```

**Comment by And-0** [comment] 2016-05-24 19:14
Using the provided steps I was able to reproduce this 100% in Chrome and Edge, but not in Firefox (both Windows 10).

**Comment by johnrees** [comment] 2016-06-04 18:40
Also happening in OS X Chrome. This should work if you need a quick hacky fix

```javascript
var game;
window.onload = function () {
  game = new Phaser.Game();

  game.state.add('play', Play);
  game.state.start('play');
};


function Play() {}
Play.prototype = {
  preload: function() {
      this.load.audio('button_press', 'button_press.wav');
      this.load.image('button_sound', 'button_sound.png');
      this.load.image('button_mute', 'button_mute.png');
  },

  create: function() {
      var that = this;
      this.clickSound = game.sound.add('button_press');

      // add signal listeners to the mute event
      this.game.sound.onMute.add(this.onMute, this);
      this.game.sound.onUnMute.add(this.onUnMute, this);
      //

      this.muteButton = game.add.button(100, 100, 'button_mute', function(){
        this.game.sound.mute = !this.game.sound.mute;
      }, this)

      this.muteButton = game.add.button(400, 100, 'button_sound', function(){
          this.clickSound.play();
      }, this)
  },

  // added methods
  onMute: function() {
    this.game.sound.masterGain.disconnect();
  },

  onUnMute: function() {
    this.game.sound.masterGain.connect(this.game.sound.context.destination);
  }
  //
};
```

**Comment by jaapaurelio** [comment] 2016-07-12 10:20
@johnrees Using your code in an isolated environment works fine but not in my app. Maybe because I have multiple sound manager. I proper fix would be great.

**Comment by photonstorm** [comment] 2017-04-20 12:33
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.

**Closed by photonstorm** 2017-04-20 12:33 UTC
Labels: Audio, needs checking
