### ISSUE TITLE
Camera size in shader pipeline

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5255] opened 2020-08-08 17:06 UTC
## Version

* Phaser Version: 3.50

* Operating system: window10

* Browser: chrome/firefox

## Description

[Here](https://github.com/rexrainbow/phaser3-rex-notes/blob/eb06efed486dc513957cc2f8bbbe6e7e233a22b6/examples/test/camera-shader-with-image.js) is a test code. Game size is 800x600, will apply grayscale shader pipeline on camera.

3 cases described below:

1. Add one 800x600 (equal to game size) image 'classroom' works well
2. Add image 'classroom' and another small image 'mushroom' works well
3. Add a small image 'mushroom' only, size of camera seems **shrink** (i.e. no full game size image in this case)

    -  Use `gl_FragColor = vec4(1)` to see the size of camera in this case

**Comment by telinc1** [comment] 2020-08-14 15:32
This appears to be caused by #5251. It does not occur if the hack I've posted there is applied.

After a camera has rendered to a texture, that texture is immediately drawn to the screen using the camera's pipeline (in `postRenderCamera`). If the pipeline is affected by the bug, the texture will re-use the vertex data of whatever was drawn first. Cases 1 and 2 appear to work because the `classroom` image's vertices match up with the camera. Case 3 shrinks the texture to the size of the `mushroom` image. If the two images are swapped in the display list so that `mushroom` is drawn first, the issue occurs in all three cases.

**Comment by photonstorm** [comment] 2020-08-20 09:48
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed by photonstorm** 2020-08-20 09:48 UTC
