### ISSUE TITLE
README.md example might leave people hanging...

### ISSUE THREAD

**Issue by carystanley** [photonstorm/phaser#3274] opened 2018-02-23 00:08 UTC
You guys are awesome, very excited about Phaser v3!!!

Implemented the Example on the README.md just to get started, and thought Phaser particles were broken when I didn't see the particle effects in the picture.

The example uses Phaser.AUTO with blendMode 'ADD', and my browser ends up using WebGL, which doesn't support blendMode 'ADD'. (Took me a half hour to figure out the issue)

Was thinking it might be better to use Phaser.CANVAS in the config, or remove blendMode 'ADD' (Though it looks so cool!).

I want everyone to have a great first time experience with Phaser v3!! 😄

**Comment by photonstorm** [comment] 2018-02-23 00:11
Sorry you wasted some time on this! It's actually caused by a bug in the particle renderer that was introduced with 3.1.1, but didn't exist in 3.0.0 when the example was written. We've since fixed it, so if you build from master you'll find it works again :) and it will be released in 3.1.2 which will be out shortly!

**Closed by photonstorm** 2018-02-23 00:11 UTC

**Comment by carystanley** [comment] 2018-02-23 00:22
Awesome!! Even Better!! 😉
