### ISSUE TITLE
Incorrect pointer worldX,  worldY 

### ISSUE THREAD

**Issue by alexeymolchan** [photonstorm/phaser#3820] opened 2018-07-08 08:19 UTC
Phaser 3.10.1
Chrome 67
Both WebGL and Canvas

Pointer worldX and worldY are incorrect in cases when camera zoom more or less then 1, camera zoom is 1 and game resolution > 1.

**Comment by photonstorm** [comment] 2018-07-09 09:38
Duplicate of #3606 - please track progress on that issue.

**Closed by photonstorm** 2018-07-09 09:38 UTC
