### ISSUE TITLE
phaser 3.5.0 Emiter add texture to all other sprite

### ISSUE THREAD

**Issue by murteira** [photonstorm/phaser#3583] opened 2018-04-17 10:29 UTC
When create an emiter in version 3.4.0 works ok, but on 3.5.0 they add the same texture defined in particle to all other images in game, while executing.
```
this.emitter0 = this.add.particles("start").createEmitter({
            x: 0,
            y: 0,
            speed: { min: -800, max: 800 },
            angle: { min: 0, max: 360 },
            scale: { start: 0.5, end: 0 },
            blendMode: 'SCREEN',
            active: false,
            lifespan: 600,
            gravityY: 0
        });
        this.emitter0.setScrollFactor(1);
this.emitter0.setPosition(asteroid.x, asteroid.y);
                this.emitter0.active = true;
                this.emitter0.explode(15);
```
In this example, as soon as i call explode() all other images in game gets an "start" overlay.

**Comment by photonstorm** [comment] 2018-04-17 11:33
Would you mind turning your code into a runnable example please? (using assets from the labs if possible), because I just tried the following code and no images changed when the emitter started:

```
var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    backgroundColor: '#000',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.atlas('flares', 'assets/particles/flares.png', 'assets/particles/flares.json');
    this.load.image('logo', 'assets/sprites/phaser3-logo.png');
}

function create ()
{
    var particles = this.add.particles('flares');

    var emitter = particles.createEmitter({
        active: false,
        frame: 'blue',
        x: 200,
        y: 300,
        lifespan: 2000,
        speed: { min: 400, max: 600 },
        angle: 330,
        gravityY: 300,
        scale: { start: 0.4, end: 0 },
        quantity: 2,
        blendMode: 'ADD'
    });

    this.input.once('pointerdown', function (event) {
    
        emitter.active = true;
    
    }, this);

    this.add.image(400, 300, 'logo');
}
```

**Comment by murteira** [comment] 2018-04-17 12:01
I can't replicate this in a fiddle, maybe its because some other file in game, because i'm using Matter physics.

Is there any way so i can send you a private link? For you to test?

**Comment by photonstorm** [comment] 2018-04-17 12:02
The physics won't make any difference to the rendering. You could email me a link, but if it's a complex or large code base, I'll warn you now: I won't have time to go through it all.

**Comment by photonstorm** [comment] 2018-04-17 14:58
We can now reproduce this bug internally. The cause is an emitter with a blend mode. We're looking into it now.

**Comment by murteira** [comment] 2018-04-17 15:09
Thanks ;)


Com os melhores cumprimentos,
*Filipe Murteira*

--
Programador Freelancer  |  Web.Mobile.Game
Tel: +351 91 786 71 70
Skype: filipe_murteira
https://www.paypal.me/murteira

--
*Projecto em destaque:*
<https://www.assistente-virtual.pt/>

2018-04-17 15:59 GMT+01:00 Richard Davey <notifications@github.com>:

**Comment by photonstorm** [comment] 2018-04-17 17:18
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed by photonstorm** 2018-04-17 17:18 UTC
Labels: Priority: Urgent, Type: Bug

**Comment by murteira** [comment] 2018-04-18 14:10
Its working perfect!

Thanks for fast support!
