### ISSUE TITLE
Camera stuttering when using with camera.startFollow, a tilemap and zoom

### ISSUE THREAD

**Issue by pierpo** [photonstorm/phaser#3738] opened 2018-06-09 15:00 UTC
Hi!

I was playing around with Phaser and tried to make a Zelda-like RPG.
I chose to use a tilemap to design my map. The map is bigger than the screen, so a camera follows the player.

The thing is: the camera is very choppy!
I use the `startFollow` method.

- If I follow the player with a `lerp` value of 1 (follow the player without any delay), then the player looks smooth but the background choppy
- If I follow the player with a `lerp` value of 0.05 (follow the player with a delay), then both the player and the background look choppy

Other informations:

- my map is pretty big, but I tried with a smaller one and I still had the issue.
- I use the `arcade` physics engine
- I use a zoom of 3

**Update**: I just noticed that if I removed the zoom and put the `lerp` value of the camera to 1, the character is smooth and the background is okay (but still a little choppy).

Here is [the scene code 🖋](https://github.com/pierpo/phaser3-simple-rpg/blob/a9f6d741c1ebd997aebdb116154c573feb32d6d4/src/scenes/Main.js) and the [index.js code 📝](https://github.com/pierpo/phaser3-simple-rpg/blob/a9f6d741c1ebd997aebdb116154c573feb32d6d4/src/index.js)

And here is [a video 🎬 ](https://imgur.com/a/PgkWlu2)

Am I doing something wrong, or is it indeed an issue with Phaser?

Thanks 😊

**Comment by hexus** [comment] 2018-06-12 21:48
This can happen if your camera has its `roundPixels` property enabled.

**Comment by bonsaiheldin** [comment] 2018-06-13 11:19
I noticed this bug today, too and i can confirm that it happens even without any zoom and with disabled `roundPixels` on the camera. In my game i only have `pixelArt` enabled on the main game config which seems to round some numbers. Enabling `roundPixels` on the camera helps a bit, but it still happens.

Plus, i noticed that spritesheets get distorted, too. See [this screenshot](http://oi68.tinypic.com/2quhn5l.jpg). That's because positions of sprites don't get rounded. I expected that `pixelArt` would enable that as sprites don't seem to have have a `roundPixels` property. Same with `roundPixels` on the camera. Shouldn't `pixelArt` on the main game config do all of this because pixel games need integers?

**Comment by pierpo** [comment] 2018-06-13 11:53
Thank you all for your answers!

Do you have a recommendation to solve the issue?

**Comment by photonstorm** [comment] 2018-06-13 12:04
Sorry, my comments above were directed at @bonsaiheldin - I've not looked into the original issue yet because I can't run the example provided stand-alone, so it'll take time to re-create a local test case before I can dig in to it.

**Comment by pierpo** [comment] 2018-06-13 16:41
@photonstorm Oh... Why can't you run it? May I be of any help?

**Comment by hexus** [comment] 2018-06-13 17:06
It would help if it was immediately available as a [Codepen](https://codepen.io) or [JSBin](http://jsbin.com) that's as small as possible to reproduce the issue.

**Comment by AndreaBoeAbrahamsen** [comment] 2018-06-16 11:17
I am having a similar problem, this what happens when `this.cameras.main.startFollow(this.player, true);` round pixel is set to true on camera in version 3.10 (but not in 3.9), background tile sprite is fine, but the player character is not:
![image](https://user-images.githubusercontent.com/9437230/41498190-53954ec4-7167-11e8-89f0-62f717c5471c.png)

**Comment by photonstorm** [comment] 2018-06-25 21:48
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Closed by photonstorm** 2018-06-25 21:48 UTC
