### ISSUE TITLE
TileMaps Broken in Safari (Phaser 2.2.0/1)

### ISSUE THREAD

**Issue by neurofuzzy** [photonstorm/phaser#1439] opened 2014-12-10 01:20 UTC
TileMaps are very broken in Safari, and it seems to be due to 1 line of code which, if I comment it out, makes everything work fine. I'd create a PR but I do not know exactly how this particular rendering flag is used:
 
The line is here:
 
https://github.com/photonstorm/phaser/blob/master/src/tilemap/TilemapLayer.js#L677
 
In method: `Phaser.TilemapLayer.prototype.shiftCanvas`
    
    context.globalCompositeOperation = 'copy';

Example:
 
http://jsfiddle.net/zq8hn23g/6/
 
This works fine in all browsers except Safari. If you run the example, then click and drag on the canvas, you'll see the tilemap flicker in and out of visibility.
 
Please let me know if you need any more info.

**Comment by photonstorm** [comment] 2015-01-05 13:34
Hmm I've merged in the latest PR but I now see the following happen in all tilemap examples:

[map screengrab](https://www.dropbox.com/s/fqz5ghzcj44342a/maps.png)

Maybe something didn't merge correctly? This happens in Chrome, FF, etc.

**Comment by DanielHudson** [comment] 2015-01-05 13:54
enableScrollDelta = true fixes that in Safari and Chrome

**Comment by photonstorm** [comment] 2015-01-05 14:37
If that's the case it probably needs to be the default setting. Which I'm assuming will bork the optimisation it introduced.

**Comment by photonstorm** [comment] 2015-01-05 14:39
Actually I've just checked and `enableScrollDelta` is already enabled by default and it still happens in Chrome (on Windows, not tested OS X yet).

**Comment by photonstorm** [comment] 2015-01-05 14:42
Setting it to `false` fixes the issue. The property was there and set to `true` as default in 2.2.1 though and didn't exhibit this issue, so it's a regression most likely from the Safari double-copy fix.

**Comment by pnstickne** [comment] 2015-01-05 16:17
@photonstorm Does `layer.renderSettings.copyCanvas` contain a DOM canvas element?

**Comment by pnstickne** [comment] 2015-01-05 16:20
@photonstorm That is bad - it is caused because the previous area is not cleared, and it "smells" like something got merged bonkers. I'll take a look at it when I get home tonight.

Since it is Chrome on windows, that should be using the "direct" method. Looking at `theLayer.renderSettings.copyCanvas` will be undefined if it is a direct bitblt.

**Comment by photonstorm** [comment] 2015-01-05 17:28
Yes `copyCanvas` is undefined, so it's definitely using the bitblt code path. Even so, in Chrome it appears as in the screen shot posted above.

Adding `game.device.canvasBitBltShift = false;` before creating the layer fixes it. It happens in Canary (41.0.22650.0) and Chrome (39.0.2171.95) both on Windows.

**Comment by photonstorm** [comment] 2015-01-16 17:42
Was going to close this off, as the PR was merged into 2.2.2, but it didn't actually fix it!

Someone on the forum reported that the Examples were still broken in Safari. I checked them out and they're better than before, but still don't work properly. In some of them the map will scroll horizontally perfectly, but as soon as you scroll vertically you get a big black area at the bottom. This is easy to see in the 'csv test' one. The 'raycast' one works fine as its all horizontal.

In SciFly strangely it screws up as soon as you scroll down, but then scrolling to the right brings the display back a little. Performance is shocking though, so not sure what's up there!

**Comment by pnstickne** [comment] 2015-01-20 01:10
Arg *grumble grumble*.

I've broken down and am getting an "iDevice" this week.
I should be able to resolve the issues in Safari then.

The scrolling-in-one-direction issue sounds like yet another oddity/incompatibility and I can only go "sigh" wrt the performance.

**Comment by photonstorm** [comment] 2015-01-20 01:40
The scrolling-one-direction blackness was in Safari on OS X, so yeah desktop. Chrome on the same Mac works flawlessly.

*fucking apple*

**Comment by pnstickne** [comment] 2015-01-20 01:46
*cough* occurs on a desktop other than Safari *cough*

**Closed** 2015-02-08 23:31 UTC
