### ISSUE TITLE
Padding text issue on Firefox

### ISSUE THREAD

**Issue by xbelanch** [photonstorm/phaser#5636] opened 2021-04-01 10:31 UTC
## Version

* Phaser Version: v3.54.0 (WebGL | Web Audio)

* Operating system: Windows 10

* Browser: Firefox 87.0 (64-bit)

## Description

Padding text object is not working as expected on Firefox 87.0. See screenshots below:

Firefox 87.0:

![Screenshot_2021-04-01 Resolutions](https://user-images.githubusercontent.com/23429/113281052-65527180-92e5-11eb-9551-11187b87920d.png)

Microsoft Edge 89.0.774.63:

![descargar](https://user-images.githubusercontent.com/23429/113281074-6b485280-92e5-11eb-8b95-8004102d6d0f.png)

Must say this issue not happens on iOS Firefox 33.

**Comment by photonstorm** [comment] 2021-04-01 13:09
Duplicate of #5625 - FF / extension issue.

**Closed by photonstorm** 2021-04-01 13:09 UTC
